from pathlib import Path
import json
import re

root = Path(__file__).resolve().parents[1]
source = (root / 'config/image-prompts.txt').read_text()
labels = {
    'SHARED_POSITIVE': '[SHARED POSITIVE]',
    'SHARED_NEGATIVE': '[SHARED NEGATIVE]',
    'PEOPLE_POSITIVE': '[PEOPLE POSITIVE]',
    'PEOPLE_NEGATIVE': '[PEOPLE NEGATIVE]',
    'NON_PEOPLE_POSITIVE': '[NON-PEOPLE POSITIVE]',
    'NON_PEOPLE_NEGATIVE': '[NON-PEOPLE NEGATIVE]',
    'PRIORITY_APPLICATION': 'PRIORITY & APPLICATION',
}
markers = sorted(labels.values(), key=len, reverse=True)
blocks = {}
for key, label in labels.items():
    pattern = r'^' + re.escape(label) + (r'\s*$' if key == 'PRIORITY_APPLICATION' else r'[^\n]*')
    match = re.search(pattern, source, re.M)
    if not match:
        raise ValueError(f'Missing prompt section: {label}')
    ends = [m.start() for marker in markers if (m := re.search(r'^' + re.escape(marker) + r'(?:[^\n]*)', source[match.end():], re.M))]
    file_end = re.search(r'^END OF FILE\s*$', source[match.end():], re.M)
    if file_end:
        ends.append(file_end.start())
    end = match.end() + min(ends) if ends else len(source)
    blocks[key] = source[match.start():end].rstrip('\n')
(root / 'apps/image-prompt-library.js').write_text('// Generated by scripts/build-image-prompts.py; edit config/image-prompts.txt.\nwindow.IdealImagePromptLibrary = Object.freeze(' + json.dumps(blocks, ensure_ascii=False, indent=2) + ');\n')
