from pathlib import Path
import json
root = Path(__file__).resolve().parents[1]
source = (root / 'config/image-prompts.txt').read_text()
parts = source.split('=' * 60)
keys = ['CLASSIFICATION_RULES', 'GLOBAL_POSITIVE', 'GLOBAL_NEGATIVE'] + [f'{category}_{polarity}' for category in ['HUMAN', 'ANIME', 'FOOD', 'LANDSCAPE', 'ARCHITECTURE', 'PRODUCT', 'GRAPHIC', 'GAME3D'] for polarity in ['POSITIVE', 'NEGATIVE']]
blocks = [parts[i + 1].strip('\n') for i in range(1, len(parts) - 1, 2) if parts[i].strip() != 'END OF PROMPT LIBRARY']
assert len(blocks) == len(keys), 'Unexpected prompt library sections'
(root / 'apps/image-prompt-library.js').write_text('// Generated by scripts/build-image-prompts.py; edit config/image-prompts.txt.\nwindow.IdealImagePromptLibrary = Object.freeze(' + json.dumps(dict(zip(keys, blocks)), ensure_ascii=False, indent=2) + ');\n')
