(() => {
  const storageKey = 'ideal-machine-if-shikong';
  const chatKey = 'ideal-machine-chat';
  const writingStyleKey = 'ideal-machine-if-writing-styles';
  const app = document.createElement('div'); app.className = 'ifspace-app'; document.body.appendChild(app);
  let state = readState(); let page = 'home'; let activeId = ''; let busy = false; let lastRandomWorld = -1; let createDraft = null;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  function readState() { try { const value = JSON.parse(localStorage.getItem(storageKey) || '{}'); return { spaces:Array.isArray(value.spaces) ? value.spaces : [], roleId:value.roleId || '' }; } catch { return { spaces:[], roleId:'' }; } }
  function save() { localStorage.setItem(storageKey, JSON.stringify(state)); }
  function readChat() { try { const value = JSON.parse(localStorage.getItem(chatKey) || '{}'); return { contacts:Array.isArray(value.contacts) ? value.contacts : [], profiles:Array.isArray(value.profiles) ? value.profiles : [], chats:value.chats && typeof value.chats === 'object' ? value.chats : {} }; } catch { return { contacts:[], profiles:[], chats:{} }; } }
  function roles() { return readChat().contacts.map(item => ({ ...item, nickname:roleRealName(item) })); } function role() { return roles().find(item => item.id === state.roleId) || roles()[0]; }
  function roleRealName(item) { return item?.realName || item?.name || '角色'; }
  function boundProfile(roleId) { const data = readChat(); const profileId = data.chats?.[roleId]?.profileId || ''; return data.profiles.find(item => item.id === profileId); }
  function userRealName(roleId) { const profile = boundProfile(roleId); return profile?.realName || profile?.name || '用户'; }
  const request = (input, init = {}) => {
    let next = init;
    try {
      const payload = JSON.parse(init.body);
      const system = payload.messages?.find(item => item.role === 'system');
      const activeSpace = state.spaces.find(item => item.id === activeId);
      const currentRole = roles().find(item => item.id === (activeSpace?.roleId || state.roleId)) || role() || {};
      const currentUser = boundProfile(currentRole.id) || {};
      if (system && window.IdealMachineRoleUserContext) {
        system.content = `${window.IdealMachineRoleUserContext(currentRole, currentUser)}\n\n${system.content}`;
        next = { ...init, body:JSON.stringify(payload) };
      }
    } catch {}
    return window.IdealMachineFetch ? window.IdealMachineFetch(input, { ...next, idealScope:'ifshikong' }) : window.fetch(input, next);
  };
  const fetch = request;
  function avatar(item) { return item?.avatar ? `<img src="${esc(item.avatar)}" alt="">` : esc(roleRealName(item).slice(0, 1)); }
  function uid() { return `if-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`; }
  const randomWorlds = [
    { premise:'如果我们在十年后的同一天再次相遇', setting:'近未来 · 雨夜城市', opening:'末班列车停运后，我们同时走进了那间没有招牌的咖啡馆' },
    { premise:'如果所有没说出口的话都会变成星星', setting:'宇宙寓言 · 静谧浪漫', opening:'今晚的天空突然多出一颗只属于我们的星' },
    { premise:'如果时间每天都会在凌晨三点倒退一小时', setting:'时间循环 · 都市悬疑', opening:'第三十一次醒来时，桌上的纸条终于换了一句话' },
    { premise:'如果我们是两个敌对星球最后的幸存者', setting:'星际废墟 · 克制科幻', opening:'通讯器沉默了七年，却在今天收到一个陌生坐标' },
    { premise:'如果那次告别从来没有发生', setting:'温柔日常 · 平行人生', opening:'推开家门时，你仍像往常一样问我要不要一起吃晚饭' },
    { premise:'如果记忆可以被寄存在月球背面', setting:'黑白科幻 · 记忆迷宫', opening:'管理员递给我一只写着你名字的银色盒子' },
    { premise:'如果这座城市只在我们入睡后出现', setting:'梦境都市 · 超现实', opening:'午夜十二点，窗外第一次亮起了不存在的街灯' },
    { premise:'如果我们共同经营一颗只有两个人的小行星', setting:'太空生活 · 治愈日常', opening:'清晨六点，温室警报响了，而你还抱着枕头不肯起床' },
    { premise:'如果我们在高中毕业那天交换了人生', setting:'青春校园 · 成长群像', opening:'新学期点名时，老师念出的名字属于我，座位上的人却是你' },
    { premise:'如果整座学校只有我们记得昨天发生过什么', setting:'校园悬疑 · 时间异常', opening:'早读铃响起，同桌再次问出了昨天一模一样的问题' },
    { premise:'如果我们成了同一家公司的竞争对手', setting:'都市职场 · 慢热关系', opening:'最终提案名单公布时，我们的名字被印在了同一行' },
    { premise:'如果离职后的第一份工作是替你经营旧书店', setting:'城市日常 · 温暖治愈', opening:'开门第一天，我在收银台下发现了你五年前留下的账本' },
    { premise:'如果所有谎言都会在说出口后留下实体证据', setting:'犯罪悬疑 · 冷峻现实', opening:'审讯桌上突然多出一张没人带进来的车票' },
    { premise:'如果我们必须在日落前找出谁改写了记忆', setting:'心理悬疑 · 限时调查', opening:'醒来时，我的手腕上写着你的名字和一个倒计时' },
    { premise:'如果这间旅馆的每扇门都通向不同年代', setting:'时空旅店 · 单元故事', opening:'前台递来一把标着一九三七年的铜钥匙' },
    { premise:'如果我们可以给过去的自己寄一封信', setting:'时间通信 · 情感剧情', opening:'邮筒退回了我的信，信封背面却多了你的笔迹' },
    { premise:'如果末日之后只有一座电台仍在播音', setting:'末日生存 · 公路旅程', opening:'汽车快没油时，收音机里传来了你的天气预报' },
    { premise:'如果植物一夜之间占领了所有城市', setting:'生态末日 · 绿色废墟', opening:'藤蔓顶开地铁出口时，我们听见地下还有人在敲门' },
    { premise:'如果每个人成年后都会获得一种无用的超能力', setting:'都市奇幻 · 轻喜剧', opening:'我的能力觉醒报告上写着：能准确找到你丢失的袜子' },
    { premise:'如果我们的影子拥有彼此相反的性格', setting:'现代奇幻 · 双重关系', opening:'路灯亮起后，你的影子先一步握住了我的手腕' },
    { premise:'如果童话王国已经进入破产清算', setting:'黑色童话 · 荒诞喜剧', opening:'王宫拍卖会上，我们同时举牌竞拍那面失去魔法的镜子' },
    { premise:'如果龙决定退休并在人类城市开餐馆', setting:'日常奇幻 · 美食经营', opening:'试营业第一晚，你端出的汤把菜单烧出了一个洞' },
    { premise:'如果我们在江湖中分别效忠敌对门派', setting:'古代武侠 · 身份对立', opening:'雨停之前，我必须决定要不要把剑还给你' },
    { premise:'如果一封赐婚圣旨把两个陌生人绑在一起', setting:'古代朝堂 · 先婚后识', opening:'宣旨的人刚走，你便把府门钥匙推到了我面前' },
    { premise:'如果我们经营一家专门替妖怪解决麻烦的客栈', setting:'东方志怪 · 市井日常', opening:'今晚第一位客人没有影子，却点了两个人的饭' },
    { premise:'如果修仙世界最重要的考试允许普通人参加', setting:'仙侠学院 · 逆袭成长', opening:'测灵石毫无反应时，只有你看见它背后裂开了一道缝' },
    { premise:'如果城市由一套会预测爱情的算法管理', setting:'赛博都市 · 情感反抗', opening:'系统宣布我们匹配度为零，却同时下达了同居指令' },
    { premise:'如果记忆可以像商品一样自由交易', setting:'近未来商业 · 伦理悬疑', opening:'拍卖目录的最后一项，是我从未经历过的与你的婚礼' },
    { premise:'如果仿生人开始梦见同一个不存在的人', setting:'硬核科幻 · 意识谜题', opening:'检修记录显示，你昨夜说出了只有我知道的地址' },
    { premise:'如果月球背面藏着一座废弃城市', setting:'太空考古 · 孤寂探索', opening:'舱门打开后，城市广场的大钟重新开始走动' },
    { premise:'如果我们在一艘永远靠不了岸的船上醒来', setting:'海洋冒险 · 封闭谜局', opening:'船长室的航海图上，所有陆地都被人涂掉了' },
    { premise:'如果这趟公路旅行没有预定终点', setting:'现实公路 · 关系修复', opening:'导航失去信号后，你第一次问我要不要决定方向' },
    { premise:'如果小镇上的每个人都在隐瞒同一件事', setting:'小镇悬疑 · 熟人社会', opening:'葬礼结束后，墓碑上的日期被人悄悄改晚了一年' },
    { premise:'如果我们继承了一栋只在雨天出现的房子', setting:'哥特住宅 · 家族秘密', opening:'暴雨落下时，空地上亮起了一扇二楼的窗' },
    { premise:'如果所有恐惧都能被量化并公开显示', setting:'社会寓言 · 心理惊悚', opening:'广场屏幕公布数据时，你的数值突然变成了零' },
    { premise:'如果我们被迫参加一档不能说谎的真人秀', setting:'娱乐圈 · 荒诞喜剧', opening:'直播灯亮起，主持人递来的第一张问题卡写着彼此的名字' },
    { premise:'如果一支垫底战队只剩我们两名正式队员', setting:'电竞成长 · 热血群像', opening:'赛季报名截止前十分钟，训练室突然有人敲门' },
    { premise:'如果我们在战争结束前一天收到停战消息', setting:'历史架空 · 战地剧情', opening:'信使倒在城门外，手中公文的印章属于敌军' },
    { premise:'如果一家人可以投票删除共同记忆', setting:'家庭伦理 · 现实剧情', opening:'今晚的议题是删除母亲离开那天，而你投了反对票' },
    { premise:'如果我们在菜市场共同照顾一只走失的猫', setting:'市井生活 · 轻松日常', opening:'卖鱼摊收摊时，那只猫把一串钥匙放在了我们脚边' },
    { premise:'如果每场梦都会在第二天成为新闻', setting:'梦境现实 · 超现实悬疑', opening:'晨间新闻播出的事故，正是你昨晚没有讲完的梦' },
    { premise:'如果死亡的人可以回来完成一件小事', setting:'温柔奇幻 · 告别故事', opening:'门铃响起时，桌上的旧钟停在了你离开的那一分钟' },
    { premise:'如果我们只能通过一本共享日记交流', setting:'书信叙事 · 慢热情感', opening:'空白页上出现第一句话时，我们相隔整整一百年' },
    { premise:'如果这座城市每天随机交换两个人的身份', setting:'身份错位 · 都市喜剧', opening:'手机解锁后，通讯录里所有人都在叫我你的名字' },
    { premise:'如果我们每次推开客栈房门都会进入不同朝代', setting:'古风无限流 · 时空闯关', opening:'掌柜递来第七把钥匙，门牌上写着一个尚未出现的年号' },
    { premise:'如果一座古城每逢月蚀就会重演灭城前夜', setting:'古风悬疑 · 循环破局', opening:'更鼓第三次响起时，我们发现城门上的箭痕换了位置' },
    { premise:'如果我们必须在七场古代婚礼中找出唯一真实的一场', setting:'古风无限流 · 身份谜局', opening:'喜轿落地后，盖头外传来的却是自己的声音' },
    { premise:'如果我们在同一座科举考场答题，每道题都会改变彼此的过去', setting:'古代科举 · 规则奇谈', opening:'其中一人写下第一个字，另一个人手中的旧伤随即消失了' },
    { premise:'如果被废弃的冷宫只在下雪时接纳活人', setting:'宫廷志怪 · 秘密调查', opening:'宫门自行打开，雪地里已有两串属于我们的脚印' },
    { premise:'如果新帝登基当日收到了一封十年后的退位诏书', setting:'古代权谋 · 时间悬案', opening:'玉玺尚未落下，诏书末尾先出现了我们的名字' },
    { premise:'如果我们分别是史书中被抹去的将军与谋士', setting:'历史架空 · 战争权谋', opening:'残卷重见天日的那晚，边关同时送来一封求援信' },
    { premise:'如果江湖上每把名剑都记得上一任主人的死因', setting:'武侠探案 · 器物记忆', opening:'剑刚出鞘，客栈二楼便传来一个死去多年的人的咳嗽声' },
    { premise:'如果我们押送的不是犯人，而是一段会说话的国运', setting:'古风公路 · 奇幻冒险', opening:'囚车越过第一座桥时，车中人叫出了皇帝幼年的名字' },
    { premise:'如果一纸和离书必须由未来的我们共同签字', setting:'古代情感 · 时间错位', opening:'衙门书吏摊开文书，落款处已有一道年迈的笔迹' },
    { premise:'如果所有进入山庄的人都会忘记自己来此的目的', setting:'古风无限流 · 封闭山庄', opening:'醒来时，袖中只剩一张写着“不要相信昨夜”的纸条' },
    { premise:'如果我们在同一场梦里参加一场没有终点的殿试', setting:'梦境古风 · 无限考场', opening:'金殿上的考官没有脸，第一题却问起我们共同隐瞒的事' },
    { premise:'如果每通过一道门，就必须留下一个真实姓名', setting:'无限流 · 身份代价', opening:'第五道门亮起时，登记册上只剩最后一个空位' },
    { premise:'如果午夜地铁的每一站都是一种可能的人生', setting:'都市无限流 · 选择困境', opening:'广播报出不存在的站名，车窗外出现了我们从未住过的家' },
    { premise:'如果副本结束后只有一个人能保留全部记忆', setting:'无限流 · 记忆博弈', opening:'结算屏幕亮起，奖励栏里写着“忘记对方”' },
    { premise:'如果酒店每层楼都遵守一套互相冲突的规则', setting:'规则怪谈 · 封闭逃生', opening:'电梯停在十三层，门外贴着“本楼没有电梯”' },
    { premise:'如果我们醒在一场已经失败过九十九次的救援任务里', setting:'无限循环 · 灾难救援', opening:'警报响起前十秒，通讯器里传来了上一次的遗言' },
    { premise:'如果每个房间都会读取进入者最想隐瞒的记忆', setting:'心理无限流 · 双人闯关', opening:'第一扇门没有锁，门上却出现了只有我们知道的日期' },
    { premise:'如果规则要求我们互不相识，系统却判定我们撒谎', setting:'规则怪谈 · 关系谜题', opening:'广播第三次警告后，两人的手环同时变成红色' },
    { premise:'如果通关条件是让故事里的反派主动放弃结局', setting:'叙事无限流 · 角色觉醒', opening:'剧本翻到最后一页，反派在空白处写下了求救地址' },
    { premise:'如果每次死亡都会回到同一顿尚未吃完的晚餐', setting:'时间循环 · 家庭悬疑', opening:'汤仍冒着热气，桌下却多出了一把沾水的钥匙' },
    { premise:'如果废弃商场在停电后会重新开始营业', setting:'都市怪谈 · 生存探索', opening:'应急灯熄灭后，广播欢迎我们成为今晚第一批顾客' },
    { premise:'如果凌晨四点收到的外卖来自明天', setting:'都市奇谈 · 时间快递', opening:'袋中餐盒还热着，小票背面写着明早的事故地点' },
    { premise:'如果整栋公寓只有我们听得见墙后的倒计时', setting:'都市悬疑 · 邻里秘密', opening:'倒计时归零那刻，隔壁搬走三年的住户敲响了门' },
    { premise:'如果失踪人口会短暂出现在城市的广告屏上', setting:'都市探案 · 科技异象', opening:'红灯亮起时，屏幕中的人突然转头看向我们所在的车' },
    { premise:'如果一家便利店可以出售被放弃的人生选择', setting:'都市寓言 · 深夜日常', opening:'收银员把没有条码的盒子推来，说这是我们去年没选的路' },
    { premise:'如果我们共同租下的房间每天都会多出一件旧物', setting:'合租日常 · 记忆悬疑', opening:'第六天早晨，餐桌上出现了一张两人都没拍过的合照' },
    { premise:'如果城市停摆一天，只有我们仍能自由行动', setting:'都市静止 · 关系冒险', opening:'十字路口的雨悬在半空，远处却有人移动了一把伞' },
    { premise:'如果公司年会抽中的奖品是一段同事的真实记忆', setting:'职场黑色喜剧 · 记忆伦理', opening:'投影亮起后，会议室里播放的是老板从未公开的辞职信' },
    { premise:'如果我们被调入一个专门处理“不可能投诉”的部门', setting:'奇幻职场 · 单元案件', opening:'第一位来访者要求退还被星期一偷走的三个小时' },
    { premise:'如果我们的加班时间可以互相兑换成未来寿命', setting:'职场寓言 · 现实科幻', opening:'工资单多出一栏，其中一人的余额显示为负数' },
    { premise:'如果毕业照里每天都会少一个人', setting:'校园怪谈 · 青春悬疑', opening:'班群争论到深夜，只有我们记得照片最右边原本站着谁' },
    { premise:'如果全校只有我们没有收到未来职业通知书', setting:'校园科幻 · 成长选择', opening:'广播逐一念完名字后，讲台上还剩两只没有署名的信封' },
    { premise:'如果社团活动室能收到十年前学生的留言', setting:'校园通信 · 双线青春', opening:'擦掉黑板上的值日表后，下面露出一句今天刚写的警告' },
    { premise:'如果高考结束后，只有我们记得那个被所有人忘记的同学', setting:'青春悬疑 · 集体记忆', opening:'空座位被搬走前，我们从桌洞里找到一封写给两人的信' },
    { premise:'如果我们照顾的孩子声称认识年轻时的父母', setting:'家庭奇幻 · 代际关系', opening:'孩子从旧相册中指出一栋从未有人提起的房子' },
    { premise:'如果一家人必须共同生活一天才能继承一段记忆', setting:'家庭伦理 · 封闭剧情', opening:'律师锁上老宅大门，把一盘没有标签的录像带放到桌上' },
    { premise:'如果每次争吵都会让家中一件物品彻底消失', setting:'家庭寓言 · 关系修复', opening:'碗落地却没有碎，只在所有人的视线里消失了' },
    { premise:'如果我们收养的流浪狗每天都会带回一条未来新闻', setting:'治愈日常 · 轻奇幻', opening:'它今天叼回的报纸头版上，印着这间屋子的地址' },
    { premise:'如果海边民宿的客人都在等待同一艘不存在的船', setting:'海岸悬疑 · 群像故事', opening:'退潮后，沙滩上出现了通向海里的登船队伍' },
    { premise:'如果我们经营的餐厅只为人生最后一次见面的人开门', setting:'美食治愈 · 告别单元剧', opening:'打烊后门铃再次响起，预订单上写着两位早已失联的客人' },
    { premise:'如果小镇邮局会退回所有言不由衷的信', setting:'小镇日常 · 温柔奇幻', opening:'退件堆到柜台边时，我们同时认出了最上面的笔迹' },
    { premise:'如果每场雨都会带回一段被遗忘的声音', setting:'雨城奇幻 · 情感悬疑', opening:'屋檐开始滴水，录音机里传出了我们童年时的争执' },
    { premise:'如果末日避难所的物资足够，名单却多出一个人', setting:'末日封闭 · 身份悬疑', opening:'点名结束后，仓库深处有人回答了不存在的编号' },
    { premise:'如果废土上的最后一列火车只能向记忆更少的方向行驶', setting:'废土公路 · 记忆代价', opening:'列车停下时，驾驶台要求我们各自交出一段往事' },
    { premise:'如果太阳熄灭前，人类只剩七次日出', setting:'末日科幻 · 倒计时关系', opening:'第一场人造黎明升起时，观测站收到一束来自深空的回复' },
    { premise:'如果所有避难城都拒绝承认外面的世界仍有人活着', setting:'反乌托邦 · 生存调查', opening:'城墙广播宣布荒野无人，门外却响起约定好的三声敲击' },
    { premise:'如果我们是空间站里唯二没有冬眠记录的人', setting:'星际悬疑 · 封闭空间', opening:'主控系统恢复后，航行日志显示两人已经醒过十二次' },
    { premise:'如果一颗行星会根据访客的关系改变地貌', setting:'星际探索 · 关系寓言', opening:'我们争执后，返回舱与营地之间突然升起一道峡谷' },
    { premise:'如果宇宙尽头是一座保存所有未发生故事的图书馆', setting:'宇宙奇幻 · 叙事探索', opening:'管理员递来一本空白书，书脊上却印着我们的真名' },
    { premise:'如果两艘敌对飞船必须共享同一套生命维持系统', setting:'硬科幻 · 敌对合作', opening:'氧气曲线开始下降，对方舰桥发来了一份没有署名的方案' },
    { premise:'如果我们发现地球其实是一艘已经航行千年的飞船', setting:'宇宙谜题 · 文明真相', opening:'地震过后，山体内部露出一扇仍在运行的舱门' },
    { premise:'如果仿生人可以继承人类未完成的承诺', setting:'近未来伦理 · 情感剧情', opening:'遗产清单最后一项不是财物，而是一句必须亲口说出的话' },
    { premise:'如果梦境治疗会把两名陌生人的记忆接在一起', setting:'心理科幻 · 记忆交错', opening:'治疗结束后，我们同时记起了一间现实中不存在的厨房' },
    { premise:'如果每个人都能看见关系的剩余期限', setting:'现代奇幻 · 关系抉择', opening:'人群头顶都有数字，只有我们看见彼此的位置是一片空白' },
    { premise:'如果说出真心话会随机改变一条城市规则', setting:'荒诞都市 · 情感喜剧', opening:'那句话出口后，全城的红绿灯开始只对我们闪烁' },
    { premise:'如果我们参加的恋爱节目其实是一场失踪案调查', setting:'娱乐圈悬疑 · 身份伪装', opening:'第一次约会的任务卡背面，印着三年前的寻人启事' },
    { premise:'如果过气演员只能在别人的梦里继续表演', setting:'娱乐圈奇幻 · 梦境剧情', opening:'首演散场后，唯一记得完整台词的人坐在最后一排' },
    { premise:'如果一场直播会提前播出参与者明天的选择', setting:'直播悬疑 · 时间预告', opening:'弹幕开始倒数，画面中的我们却走向了两条不同的路' },
    { premise:'如果我们共同开发的游戏开始删除现实中的地点', setting:'游戏现实 · 科技悬疑', opening:'测试服移除旧车站后，城市地图上也失去了那个站名' },
    { premise:'如果只有失败过的人才能看见隐藏任务', setting:'成长冒险 · 轻无限流', opening:'排行榜公布后，我们脚边同时亮起一条没人注意的路线' },
    { premise:'如果一个没有魔法的人被选为魔法学院的校长', setting:'学院奇幻 · 荒诞经营', opening:'开学典礼上，校徽拒绝发光，却主动打开了禁书库' },
    { premise:'如果龙族的成年礼要求在人类城市找到一份正式工作', setting:'现代奇幻 · 职场喜剧', opening:'面试官问起特长时，候选人的简历边缘开始冒烟' },
    { premise:'如果妖怪在人间生活必须每月提交一份情绪报告', setting:'东方奇幻 · 都市日常', opening:'月底系统催报时，我们发现整条街的悲伤数值同时归零' },
    { premise:'如果神明失去信徒后需要到社区服务中心登记', setting:'神话现代化 · 市井喜剧', opening:'窗口叫到下一号，一位旧神拿出了已经过期千年的证件' },
    { premise:'如果我们能听见旧物对上一位主人保留的最后一句话', setting:'物件奇谈 · 单元故事', opening:'二手钟表恢复走动后，说出的第一句话提到了今天的日期' },
    { premise:'如果书中的配角可以投票更换故事主角', setting:'元叙事 · 轻喜剧', opening:'章节标题消失后，所有人的名字旁都出现了一只投票框' },
    { premise:'如果侦探与嫌疑人醒来后交换了全部证词记忆', setting:'本格探案 · 记忆错位', opening:'审讯开始前，我们同时指出了只有凶手才知道的位置' },
    { premise:'如果法庭允许死者通过物证回答三个问题', setting:'司法奇幻 · 案件推理', opening:'第一件证物亮起时，它拒绝回答关于凶手的问题' },
    { premise:'如果一宗旧案的所有证人都在同一天收到新的不在场证明', setting:'现实探案 · 群体秘密', opening:'档案袋送到办公室时，里面的照片拍摄于明天' },
    { premise:'如果婚礼策划师能提前看见每段婚姻的一个结局', setting:'都市情感 · 单元剧情', opening:'新客户进门后，我们看到的却是彼此多年后的餐桌' },
    { premise:'如果分手后的共同物品必须经过一场公开拍卖', setting:'现实情感 · 黑色幽默', opening:'第一件拍品是一把旧钥匙，竞价人中出现了陌生的第三个人' },
    { premise:'如果我们只能在彼此最忙的时候遇见', setting:'都市慢热 · 时间错位', opening:'会议结束已近午夜，电梯却停在了不属于任何公司的楼层' },
    { premise:'如果一对宿敌被迫共同抚养一颗会说话的蛋', setting:'奇幻喜剧 · 敌对同居', opening:'蛋壳第一次裂开时，里面的声音分别叫了我们的名字' }
  ];
  const pairRandomWorlds = randomWorlds.filter(item => {
    const text = `${item.premise} ${item.opening}`;
    const hasTwoPersonCore = /我们|两个人|两人|彼此|共同|互相|宿敌/.test(text);
    const forcesRelationship = /一家人|父母|母亲|孩子|赐婚|和离|婚礼|婚姻|恋爱节目|分手|同居指令/.test(text);
    return hasTwoPersonCore && !forcesRelationship;
  });
  const writingStyles = { natural:'自然细腻', cinematic:'电影感', literary:'文学抒情', concise:'克制简洁', suspense:'悬疑紧张', daily:'生活流' };
  const writingStylePrompts = {
    natural:'[CRAFT REFERENCES] Draw only on broad, non-copying techniques: Wang Zengqi\'s use of food, objects, weather, and local routines to make a setting credible, with feeling carried by what people do; and Chekhov\'s use of hesitation, self-correction, ineffective gestures, and material circumstances to reveal contradiction without diagnosing the character. [BLENDING METHOD] Select two or three concrete details already present in the scene, then let action and dialogue change the relationship. Narrate only what the viewpoint character can presently perceive. Do not name an emotion when behavior can carry it. Vary sentence length with the speed of action. End on a specific change that remains open to response. [ORIGINAL DEMONSTRATION — NEVER COPY OR PARAPHRASE] She returned the second set of chopsticks to the cupboard, shut the door, opened it again, and asked whether he still wanted scallions in the soup.',
    cinematic:'[CRAFT REFERENCES] Draw only on broad, non-copying techniques: the distance between surface dialogue and actual intent in Hemingway\'s Hills Like White Elephants, where pauses and evasions carry crucial information; and the clear blocking, physical action, and object states used to propel scenes in Dashiell Hammett\'s The Maltese Falcon. [BLENDING METHOD] Establish the positions of people, exits, and consequential objects, then alternate action, dialogue, and environmental consequence. Use shorter sentences under pressure and longer observation during quiet intervals. Never use camera terminology. Do not explain what the visible action has already established. [ORIGINAL DEMONSTRATION — NEVER COPY OR PARAPHRASE] The lock clicked twice. Fang Yikai did not turn around. He slid the second cup behind the newspaper.',
    literary:'[CRAFT REFERENCES] Draw only on broad, non-copying techniques: Shen Congwen\'s integration of landscape, daily order, and human fate in Border Town; Calvino\'s structural repetition and light conceptual architecture in Invisible Cities; and Virginia Woolf\'s close sensory attention, where a present object briefly opens memory before returning to the room. [BLENDING METHOD] Images must come from objects that truly exist in the current scene and must later affect meaning or action. Perception and memory may briefly overlap, but narration must promptly return to physical space and ongoing action. Keep figurative language sparse. Never announce a theme or moral. [ORIGINAL DEMONSTRATION — NEVER COPY OR PARAPHRASE] At the sixth bell, Su Qian folded the letter along its old crease. The umbrellas below had dispersed; the cut left by the paper still marked her finger.',
    concise:'[CRAFT REFERENCES] Draw only on broad, non-copying techniques: Hemingway\'s omission of explanation so facts, actions, and dialogue carry subtext; and Raymond Carver\'s use of kitchens, bills, ashtrays, and unfinished speech to create relational pressure. [BLENDING METHOD] Prefer exact verbs and concrete nouns. Remove modifiers that do not change meaning. Each paragraph completes one action or exchange without restating known information. Dialogue may be brief, but it needs a clear addressee and immediate purpose. Silence must be shown through an interrupted action, an unanswered question, or unfinished work. [ORIGINAL DEMONSTRATION — NEVER COPY OR PARAPHRASE] He finished reading the bill and placed his phone facedown. “Next month.” The refrigerator stopped humming. The tap continued to drip.',
    suspense:'[CRAFT REFERENCES] Draw only on broad, non-copying techniques: Agatha Christie\'s control over the order of clues, allowing ordinary details to acquire new meaning later; Borges\'s use of catalogues, maps, mirrored structures, and branching time; and Edgar Allan Poe\'s accumulation of pressure through enclosed spaces, recurring sounds, and altered objects. [BLENDING METHOD] Add only one verifiable fact per paragraph. Clues must arise from behavior, spatial change, object state, or conflicting testimony. Misdirection must remain retrospectively explainable; never invent the answer at the reveal. Fear should grow from narrowing choices, not exaggerated emotional vocabulary. [ORIGINAL DEMONSTRATION — NEVER COPY OR PARAPHRASE] The roster showed that no one entered the archive overnight. Fang Yikai turned it over. His signature appeared beside 3:00 a.m., and the ink had not dried.',
    daily:'[CRAFT REFERENCES] Draw only on broad, non-copying techniques: Wang Zengqi\'s attention to food, seasons, and practiced hands; Lao She\'s dialogue shaped by profession, social position, and relational distance; and Jane Austen\'s judgments, misunderstandings, and social calibration beneath polite speech. [BLENDING METHOD] Build scenes around meals, travel, errands, tidying, and pauses in work. Let relationships shift through forms of address, division of labor, avoidance, jokes, and minor friction. Dialogue may pause, self-correct, or answer sideways. Do not manufacture quotable aphorisms. [ORIGINAL DEMONSTRATION — NEVER COPY OR PARAPHRASE] Su Qian said she did not eat breakfast. Ten minutes later, she took half a slice of toast from Fang Yikai\'s plate. He moved the jam toward her without comment.'
  };
  const styleExecutionFramework = `
 [SCOPE] Apply this style to relationships, psychological change, physical action, and continuous narrative. Style governs narrative organization and verbal texture only. It must never overwrite a character's education, personality, knowledge, identity, or habitual voice.
[RESPONSIBILITY BOUNDARIES] Plot determines what happens. Character data determines what a character knows and would do. Style determines which details receive attention, when information appears, and how sentences carry relational change. Never grant a character knowledge outside the established setting. Never use narration to make the character deliver the author's opinion.
[PARAGRAPH ENGINE] Every paragraph must create a verifiable change: position, object state, new information, relational distance, an executed decision, or a revised judgment. Begin from the current scene, develop action or cognition, and end on a fact that permits the next response. Atmosphere without progression is insufficient.
[DETAIL ADMISSION RULE] Keep a detail only when it affects a choice, changes the meaning of a line, exposes a relational habit, plants a later clue, or revises the reader's judgment. Remove decorative clothing, weather, streetscape, and furnishing details with no function. Prefer precise nouns to chains of adjectives, while respecting the character's era, profession, and knowledge.
[PSYCHOLOGICAL SEQUENCE] First show the observable trigger. Then show judgment, self-defense, or hesitation. Finally let action carry the consequence. A character may misunderstand themself; narration must not turn conflict into a diagnosis or life lesson.
[DIALOGUE FUNCTION] Every spoken line must perform at least one task: ask, evade, test, refuse, confirm, redirect, or alter the relationship. Length follows character habit and scene pressure. Silence must cause a consequence and appear through interrupted action, a displaced answer, or unfinished work.
[EXAMPLE BOUNDARY] Preset examples demonstrate only information density and action order. Never copy or closely paraphrase their names, object combinations, sentence endings, or relational situations. Derive all new material from the current characters, location, era, and history.
[FINAL SELF-CHECK] Check every paragraph for concrete progression, clear pronoun reference, out-of-character knowledge, actions or thoughts imposed on the user, duplicated emotional explanation, decorative sentences removable without loss, and whether the ending preserves space for the user to act. Rewrite failures before producing the answer.`;
  const antiClichePrompt = `[ANTI-CLICHE AND ANTI-TEMPLATE RULES]
1. Do not use empty elevation, concluding morals, summaries of the user's input, serial parallelism, adjective piles, or lyrical sentences that add no information. Avoid stock phrases equivalent to “the gears of fate,” “the air seemed frozen,” or “this moment became eternal.”
2. Avoid prefabricated similes and metaphors. In Chinese output, do not use structures such as “像……一样,” “像……的……,” “像是……,” or “仿佛.” Do not use false-elevation structures such as “不是……而是……,” “这不是……,” or “那不是…….” Do not use “我看过太多” to manufacture world-weariness.
3. Never use pebbles, ripples, feathers, scalpels, needles, or branding irons as emotional or sensory metaphors. Avoid vague or inflated Chinese expressions such as “泛白,” “极其,” “一丝,” “不易察觉,” “不容置疑,” “共犯,” and “震动.” A literal object with the same name is allowed only when physically present and consequential to the scene; it may not serve as a metaphor.
4. Convert abstractions into observable mechanics: how light reaches an object, what pressure touches skin, how distance changes, how weight shifts, and what happens to breath, hands, gaze, or voice. Do not announce atmosphere or emotion for the reader.
5. Character data is a behavioral constraint, never material for self-exposition. Unless directly asked or logically required in the scene, a character must not explain, list, or advertise their background, identity, traits, abilities, or relationships. Rewrite any line that sounds like a profile, lore document, or character card. Show identity through choices, habits, tone, actions, and reactions.
6. Advance the scene through specific action, sensory fact, natural dialogue, and responses consistent with identity. Never decide the user's actions, thoughts, feelings, or dialogue. Output no analysis, writing notes, or restatement of these rules.
7. The final Chinese prose must use natural paragraphing. Each paragraph should carry one principal action, one development in dialogue, or one psychological turn. Insert a blank line between paragraphs. Never compress the response into a single wall of text.`;
  const povLabels = { first:'第一人称“我”', second:'第二人称“你”', third:'第三人称（真名或“他/她”）' };
  function narrationRule(roleName, userName, rolePov, userPov) { const povRules = { first:'first person (“我”)', second:'second person (“你”)', third:'third person (the real name or the appropriate “他/她”)' }; return `Use ${povRules[rolePov] || povRules.first} for the character “${roleName}”. Use ${povRules[userPov] || povRules.second} for the user “${userName}”. In third person, use the real name or the pronoun supported by the character data. If gender is not explicit, prefer the real name and never guess. Pronoun reference must remain unambiguous; do not confuse “我,” “你,” and names within the same paragraph. ${antiClichePrompt}`; }
  function readWritingStyles() { try { const list = JSON.parse(localStorage.getItem(writingStyleKey) || '[]'); return Array.isArray(list) ? list.filter(item => item?.id && item?.name && item?.prompt) : []; } catch { return []; } }
  function styleOptions() { return `${Object.entries(writingStyles).map(([value, label]) => `<option value="${value}">${label}</option>`).join('')}${readWritingStyles().map(item => `<option value="${esc(item.id)}">${esc(item.name)} · 自定义</option>`).join('')}`; }
  function resolveWritingStyle(id) { const custom = readWritingStyles().find(item => item.id === id); const builtInId = writingStyles[id] ? id : 'natural'; const preset = custom ? { id:custom.id, name:custom.name, prompt:custom.prompt } : { id:builtInId, name:writingStyles[builtInId], prompt:`${writingStylePrompts[builtInId]}${styleExecutionFramework}` }; const edited = app.querySelector('[data-if-style-detail]')?.value.trim(); return { ...preset, prompt:edited || preset.prompt }; }
  function mountWritingStyleDetail() { const styleField = app.querySelector('.ifspace-style-field'); const editor = app.querySelector('[data-if-style-editor]'); if (!styleField || !editor || app.querySelector('[data-if-style-detail]')) return; const wordCount = app.querySelector('[data-if-word-count]'); if (wordCount) wordCount.value = '1500'; const field = document.createElement('div'); field.className = 'ifspace-style-detail'; field.innerHTML = '<span>具体文风要求</span><textarea data-if-style-detail maxlength="5000" placeholder="具体描述语言、节奏、对白、描写重点与需要避免的表达……"></textarea><small>内置文风包含作者技法、融合方法、原创示例和完整执行规则；可以继续修改后另存。</small><button type="button" data-if-style-detail-save>保存文风</button>'; styleField.append(field, editor); const select = app.querySelector('[data-if-writing-style]'); const sync = () => { const textarea = field.querySelector('textarea'); if (textarea) textarea.value = ''; const style = resolveWritingStyle(select?.value || 'natural'); if (textarea) textarea.value = style.prompt; }; select?.addEventListener('change', sync); sync(); }
  function saveCurrentWritingStyle() { const select = app.querySelector('[data-if-writing-style]'); const prompt = app.querySelector('[data-if-style-detail]')?.value.trim(); if (!prompt) return window.alert('请先填写具体文风要求。'); const list = readWritingStyles(); const custom = list.find(item => item.id === select?.value); if (custom) { custom.prompt = prompt; localStorage.setItem(writingStyleKey, JSON.stringify(list)); window.alert(`文风“${custom.name}”已保存。`); return; } const editor = app.querySelector('[data-if-style-editor]'); const detail = app.querySelector('.ifspace-style-detail'); const promptInput = app.querySelector('[data-if-style-prompt]'); const nameInput = app.querySelector('[data-if-style-name]'); if (promptInput) promptInput.value = prompt; if (nameInput) nameInput.value = `${writingStyles[select?.value] || '自定义文风'}副本`; if (detail) detail.hidden = true; if (editor) editor.hidden = false; nameInput?.focus(); }
  function icon(type) { const paths = { plus:'<path d="M24 9v30M9 24h30"/>', back:'<path d="M30 10 16 24l14 14"/>', spark:'<path d="m24 7 4 13 13 4-13 4-4 13-4-13-13-4 13-4z"/>', send:'<path d="m8 23 31-13-9 29-7-13zM8 23l15 3"/>', close:'<path d="m14 14 20 20M34 14 14 34"/>' }; return `<svg viewBox="0 0 48 48" aria-hidden="true">${paths[type] || ''}</svg>`; }
  function rolePicker() { const list = roles(); return `<div class="ifspace-sheet"><div class="ifspace-sheet-backdrop" data-if-close-sheet></div><section><header><h2>选择参与角色</h2><button type="button" data-if-close-sheet aria-label="关闭">${icon('close')}</button></header><div class="ifspace-role-list">${list.length ? list.map(item => `<button type="button" data-if-role="${esc(item.id)}"><i>${avatar(item)}</i><span><b>${esc(roleRealName(item))}</b><small>${esc(item.identity || '角色')}</small></span><em>${item.id === state.roleId ? '✓' : '›'}</em></button>`).join('') : '<p class="ifspace-empty">请先在聊天 App 中添加角色。</p>'}</div></section></div>`; }
  function newSpace() { return `<section class="ifspace-create"><header><button type="button" data-if-home aria-label="返回">${icon('back')}</button><div><small>新的可能</small><h1>创建一个 if 时空</h1></div></header><main><div class="ifspace-create-intro"><span>时空种子 / 001</span><p>写下一个假设，或者让宇宙替你决定。</p><button type="button" data-if-random><i>✦</i><b>随机灵感</b><small>随机生成</small></button></div><label>这个世界如果……<textarea data-if-premise placeholder="例如：如果我们没有错过"></textarea></label><label>时空风格<input data-if-setting placeholder="例如：温柔日常、末日生存、古代江湖"></label><label>想从哪里开始<input data-if-opening placeholder="例如：第一次在图书馆见面"></label><div class="ifspace-create-options"><label class="ifspace-style-field">文风<div><select data-if-writing-style>${styleOptions()}</select><button type="button" data-if-style-new>＋ 新建</button></div></label><label>每次回复字数<input data-if-word-count type="number" min="50" max="5000" step="50" value="1500" inputmode="numeric" placeholder="输入字数"></label><label>角色「${esc(roleRealName(role()))}」的人称<select data-if-role-pov><option value="first" selected>第一人称 · 我</option><option value="second">第二人称 · 你</option><option value="third">第三人称 · 真名 / 他 / 她</option></select></label><label>用户「${esc(userRealName(role()?.id))}」的人称<select data-if-user-pov><option value="first">第一人称 · 我</option><option value="second" selected>第二人称 · 你</option><option value="third">第三人称 · 真名 / 他 / 她</option></select></label></div><section class="ifspace-style-editor" data-if-style-editor hidden><div><span>新建文风</span><button type="button" data-if-style-close aria-label="关闭">×</button></div><label>文风名称<input data-if-style-name maxlength="24" placeholder="例如：冷冽电影感"></label><label>具体写作要求<textarea data-if-style-prompt maxlength="5000" placeholder="描述用词、节奏、氛围、对话和叙事偏好……"></textarea></label><button type="button" data-if-style-save>保存并使用此文风</button></section><button class="ifspace-primary" type="button" data-if-create>${icon('spark')} 生成这个时空</button></main></section>`; }
  function saveWritingStyle() { const name = app.querySelector('[data-if-style-name]')?.value.trim(); const prompt = app.querySelector('[data-if-style-prompt]')?.value.trim(); if (!name || !prompt) return window.alert('请填写文风名称和具体写作要求。'); const list = readWritingStyles(); const item = { id:`custom-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, name, prompt }; list.push(item); localStorage.setItem(writingStyleKey, JSON.stringify(list)); const select = app.querySelector('[data-if-writing-style]'); if (select) { select.insertAdjacentHTML('beforeend', `<option value="${esc(item.id)}">${esc(item.name)} · 自定义</option>`); select.value = item.id; } const detailInput = app.querySelector('[data-if-style-detail]'); if (detailInput) detailInput.value = prompt; const detail = app.querySelector('.ifspace-style-detail'); if (detail) detail.hidden = false; const editor = app.querySelector('[data-if-style-editor]'); if (editor) editor.hidden = true; }
  function randomizeWorld() { const pool = pairRandomWorlds.length ? pairRandomWorlds : randomWorlds; let index = Math.floor(Math.random() * pool.length); if (pool.length > 1 && index === lastRandomWorld) index = (index + 1 + Math.floor(Math.random() * (pool.length - 1))) % pool.length; lastRandomWorld = index; const idea = pool[index]; const premise = app.querySelector('[data-if-premise]'); const setting = app.querySelector('[data-if-setting]'); const opening = app.querySelector('[data-if-opening]'); if (premise) premise.value = idea.premise; if (setting) setting.value = idea.setting; if (opening) opening.value = idea.opening; app.querySelector('.ifspace-create-intro')?.classList.remove('is-randomized'); requestAnimationFrame(() => app.querySelector('.ifspace-create-intro')?.classList.add('is-randomized')); }
  function spaceCard(item, index) { const owner = roles().find(roleItem => roleItem.id === item.roleId); return `<button class="ifspace-space-card" type="button" data-if-open="${esc(item.id)}"><i class="ifspace-planet"><span>${String(index + 1).padStart(2, '0')}</span></i><span><b>${esc(item.title || item.premise)}</b><small>${esc(item.setting || '平行世界')} · ${esc(owner ? roleRealName(owner) : item.roleName || '未选择角色')}</small><p>${esc(item.premise)}</p></span><em>↗</em></button>`; }
  function home() { const owner = role(); return `<section class="ifspace-page"><header class="ifspace-header"><div><span>平行时空</span><h1>if 时空</h1><p>去看看，另一种人生会怎样。</p></div><button class="ifspace-close" type="button" data-if-close aria-label="关闭">×</button></header><main class="ifspace-main"><section class="ifspace-hero"><div class="ifspace-cosmos" aria-hidden="true"><i class="ifspace-orbit orbit-one"></i><i class="ifspace-orbit orbit-two"></i><i class="ifspace-orbit orbit-three"></i><b class="ifspace-star star-one">✦</b><b class="ifspace-star star-two">·</b><b class="ifspace-star star-three">✶</b></div><div class="ifspace-hero-copy"><small>如果 / 宇宙</small><h2>每一个如果，<br>都是一颗新的星球。</h2><p>每个时空独立运行，不会写入原本的聊天记忆。</p></div><button type="button" data-if-new aria-label="创建一个新时空"><i class="ifspace-new-planet">＋</i><span>创建时空</span><small>新世界</small></button></section><section class="ifspace-owner"><span>参与角色</span><button type="button" data-if-role-picker><i>${avatar(owner)}</i><b>${esc(owner?.nickname || owner?.name || '选择角色')}</b><em>⌄</em></button></section><section class="ifspace-list"><div class="ifspace-section-title"><span>我的宇宙</span><b>${state.spaces.length} 颗行星</b></div>${state.spaces.length ? state.spaces.slice().reverse().map(spaceCard).join('') : '<div class="ifspace-empty-block"><div class="ifspace-empty-system" aria-hidden="true"><span class="ifspace-empty-orbit orbit-a"><i></i></span><span class="ifspace-empty-orbit orbit-b"><i></i></span><b class="ifspace-empty-sun"></b><em class="ifspace-empty-coordinate">00°00′ / 未探索</em></div><div class="ifspace-empty-copy"><span>还没有时空</span><p>你的宇宙尚未命名。<br>从第一个「如果」开始。</p></div></div>'}</section></main></section>${page === 'role-picker' ? rolePicker() : ''}`; }
  function detail(space) { const owner = roles().find(item => item.id === space.roleId) || role(); const roleName = owner?.nickname || owner?.name || '角色'; return `<section class="ifspace-detail"><header><button type="button" data-if-home aria-label="返回">${icon('back')}</button><div><small>时空 / ${esc(space.setting || '平行世界')}</small><h1>${esc(space.title || '未命名时空')}</h1></div><button type="button" data-if-delete="${esc(space.id)}" aria-label="删除时空">×</button></header><main><div class="ifspace-world-card"><div class="ifspace-world-index"><span>世界前提</span><em>编号 ${String(state.spaces.findIndex(item => item.id === space.id) + 1).padStart(2, '0')}</em></div><h2>${esc(space.premise)}</h2><p>${esc(space.opening || '故事从这里开始。')}</p></div><div class="ifspace-character"><i>${avatar(owner)}</i><div><small>角色 / 01</small><b>${esc(roleName)}</b><p>${esc(space.characterNote || '在这个时空里的角色')}</p></div></div><div class="ifspace-transcript-title"><span>对话记录</span><em>${space.messages?.length || 0} 条消息</em></div><div class="ifspace-message-list">${space.messages?.length ? space.messages.map((item, index) => `<article class="ifspace-message ${item.role === 'user' ? 'is-user' : ''}"><span>${item.role === 'user' ? '用户' : esc(roleName)} · ${String(index + 1).padStart(2, '0')}</span><p>${esc(item.content)}</p></article>`).join('') : '<div class="ifspace-empty-chat"><span>00 / 开始</span><p>时空已经建立。<br>和角色说第一句话吧。</p></div>'}</div></main><form class="ifspace-composer" data-if-chat-form><input data-if-chat-input placeholder="在这个时空里说点什么…" aria-label="消息"><button type="submit" aria-label="发送">${icon('send')}</button></form></section>`; }
  function formatDetailParagraphs() { app.querySelectorAll('.ifspace-world-card > p,.ifspace-message > p').forEach(source => { const parts = source.textContent.split(/\n+/).map(text => text.trim()).filter(Boolean); if (parts.length < 2) return; source.replaceWith(...parts.map(text => { const paragraph = document.createElement('p'); paragraph.textContent = text; return paragraph; })); }); }
  function typographyFor(space) { return { font:space?.typography?.font || 'serif', size:Math.max(12, Math.min(32, Number(space?.typography?.size) || 15)), color:/^#[0-9a-f]{6}$/i.test(space?.typography?.color || '') ? space.typography.color : '#111111', customFontName:space?.typography?.customFontName || '', customFontSource:space?.typography?.customFontSource || '' }; }
  function fontFamily(typography) { if (typography.font === 'sans') return 'Arial,"PingFang SC",sans-serif'; if (typography.font === 'mono') return 'ui-monospace,SFMono-Regular,Menlo,monospace'; if (typography.font === 'custom' && typography.customFontSource) return '"IdealIfCustom",Georgia,"Songti SC",serif'; return 'Georgia,"Songti SC",serif'; }
  function mountDetailTypography(space) { const pageElement = app.querySelector('.ifspace-detail'); const header = pageElement?.querySelector(':scope > header'); if (!pageElement || !header) return; const typography = typographyFor(space); pageElement.style.setProperty('--if-reading-font', fontFamily(typography)); pageElement.style.setProperty('--if-reading-size', `${typography.size}px`); pageElement.style.setProperty('--if-reading-color', typography.color); let fontStyle = document.querySelector('#ifspaceCustomFont'); if (!fontStyle) { fontStyle = document.createElement('style'); fontStyle.id = 'ifspaceCustomFont'; document.head.appendChild(fontStyle); } const fontSource = String(typography.customFontSource || '').replace(/["\\\r\n]/g, value => `\\${value}`); fontStyle.textContent = typography.font === 'custom' && fontSource ? `@font-face{font-family:"IdealIfCustom";src:url("${fontSource}")}` : ''; const button = document.createElement('button'); button.className = 'ifspace-type-button'; button.type = 'button'; button.dataset.ifTypography = ''; button.textContent = '字'; button.setAttribute('aria-label', '阅读设置'); header.insertBefore(button, header.lastElementChild); const panel = document.createElement('aside'); panel.className = 'ifspace-type-panel'; panel.hidden = true; panel.innerHTML = `<div><span>阅读设置</span><button type="button" data-if-typography-close aria-label="关闭">×</button></div><label>字体<select data-if-font><option value="serif" ${typography.font === 'serif' ? 'selected' : ''}>衬线体</option><option value="sans" ${typography.font === 'sans' ? 'selected' : ''}>系统黑体</option><option value="mono" ${typography.font === 'mono' ? 'selected' : ''}>等宽体</option>${typography.customFontSource ? `<option value="custom" ${typography.font === 'custom' ? 'selected' : ''}>${esc(typography.customFontName || '自定义字体')}</option>` : ''}</select></label><label class="ifspace-font-upload">导入自定义字体<input type="file" data-if-font-file accept=".woff,.woff2,.ttf,.otf,font/woff,font/woff2,font/ttf,font/otf"><b>${esc(typography.customFontName || '选择字体文件')}</b></label><label>文字大小<div><input type="range" min="12" max="32" step="1" value="${typography.size}" data-if-font-size><output>${typography.size}px</output></div></label><label>文字颜色<div><input type="color" value="${typography.color}" data-if-font-color><output>${typography.color.toUpperCase()}</output></div></label></aside>`; pageElement.appendChild(panel); }
  function saveTypography(patch) { const space = state.spaces.find(item => item.id === activeId); if (!space) return; space.typography = { ...typographyFor(space), ...patch }; save(); const pageElement = app.querySelector('.ifspace-detail'); const typography = typographyFor(space); pageElement?.style.setProperty('--if-reading-font', fontFamily(typography)); pageElement?.style.setProperty('--if-reading-size', `${typography.size}px`); pageElement?.style.setProperty('--if-reading-color', typography.color); }
  function mountDetailActions(space) { const composer = app.querySelector('.ifspace-composer'); const send = composer?.querySelector('button[type="submit"]'); const messages = Array.isArray(space.messages) ? space.messages : []; const canReroll = messages.length > 0 && messages[messages.length - 1].role === 'assistant' && !busy; if (composer && send) { const reroll = document.createElement('button'); reroll.className = 'ifspace-reroll'; reroll.type = 'button'; reroll.dataset.ifReroll = ''; reroll.disabled = !canReroll; reroll.textContent = '↻ 重写'; reroll.setAttribute('aria-label', '重新生成最新角色回复'); composer.insertBefore(reroll, send); } if (busy) { const list = app.querySelector('.ifspace-message-list'); const owner = roles().find(item => item.id === space.roleId) || role(); if (list) list.insertAdjacentHTML('beforeend', `<div class="ifspace-writing"><span>${esc(roleRealName(owner))}在撰写中</span><i></i><i></i><i></i></div>`); requestAnimationFrame(() => { const main = app.querySelector('.ifspace-detail main'); if (main) main.scrollTop = main.scrollHeight; }); } }
  function rerollLatestReply() { if (busy) return; const space = state.spaces.find(item => item.id === activeId); if (!space?.messages?.length || space.messages[space.messages.length - 1].role !== 'assistant') return; const assistant = space.messages.pop(); const user = space.messages[space.messages.length - 1]; if (!user || user.role !== 'user') { space.messages.push(assistant); return; } space.messages.pop(); save(); const input = app.querySelector('[data-if-chat-input]'); if (input) input.value = user.content; sendMessage(); }
  function labelMessageAuthors(space) { const owner = roles().find(item => item.id === space.roleId) || role(); const roleName = roleRealName(owner); const userName = space.userName || userRealName(owner?.id); app.querySelectorAll('.ifspace-message').forEach((message, index) => { const label = message.querySelector(':scope > span'); if (label) label.textContent = `${message.classList.contains('is-user') ? userName : roleName} · ${String(index + 1).padStart(2, '0')}`; }); }
  function loadingPage() { return `<section class="ifspace-loading" role="status" aria-live="polite"><div class="ifspace-loading-window" aria-hidden="true"><span class="ifspace-loading-index">IF / 00</span><i class="ifspace-loading-star star-a"></i><i class="ifspace-loading-star star-b"></i><i class="ifspace-loading-star star-c"></i><i class="ifspace-loading-star star-d"></i><div class="ifspace-loading-planet"><b></b></div><em>生成坐标中</em></div><small>正在建立新的时间线</small><h1>宇宙正在展开</h1><p>正在整理世界设定、人物关系与故事开场<br>生成完成后会自动进入这个时空</p><div class="ifspace-loading-progress"><i></i></div></section>`; }
  function restoreCreateDraft() { if (!createDraft) return; const values = { '[data-if-premise]':createDraft.premise, '[data-if-setting]':createDraft.setting, '[data-if-opening]':createDraft.opening, '[data-if-writing-style]':createDraft.styleId, '[data-if-word-count]':createDraft.wordCount, '[data-if-role-pov]':createDraft.rolePov, '[data-if-user-pov]':createDraft.userPov }; Object.entries(values).forEach(([selector, value]) => { const field = app.querySelector(selector); if (field && value != null) field.value = value; }); const detail = app.querySelector('[data-if-style-detail]'); if (detail && createDraft.stylePrompt) detail.value = createDraft.stylePrompt; }
  function render() { const space = state.spaces.find(item => item.id === activeId); if (busy && page === 'create') { app.innerHTML = loadingPage(); return; } app.innerHTML = page === 'create' ? newSpace() : page === 'detail' && space ? detail(space) : home(); if (page === 'create') { mountWritingStyleDetail(); restoreCreateDraft(); } if (page === 'detail' && space) { createDraft = null; formatDetailParagraphs(); labelMessageAuthors(space); mountDetailTypography(space); mountDetailActions(space); } }
  async function createSpace() { if (busy) return; const owner = role(); const premise = app.querySelector('[data-if-premise]')?.value.trim(); const setting = app.querySelector('[data-if-setting]')?.value.trim(); const opening = app.querySelector('[data-if-opening]')?.value.trim(); const style = resolveWritingStyle(app.querySelector('[data-if-writing-style]')?.value || 'natural'); const wordCount = Math.max(50, Math.min(5000, Number(app.querySelector('[data-if-word-count]')?.value) || 400)); const rolePov = app.querySelector('[data-if-role-pov]')?.value || 'first'; const userPov = app.querySelector('[data-if-user-pov]')?.value || 'second'; if (!owner) return window.alert('请先选择一个角色。'); if (!premise) return window.alert('请先写下一个“如果”。'); const roleName = roleRealName(owner); const userName = userRealName(owner.id); const narration = narrationRule(roleName, userName, rolePov, userPov); const config = window.IdealMachineAPI?.getConfig?.() || {}; const model = window.IdealMachineAPI?.getModel?.('ifshikong') || window.IdealMachineAPI?.getModel?.('chat'); if (!config.endpoint || !config.key || !model) return window.alert('请先在设置中配置 if时空的 AI 模型。'); busy = true; render(); try { const response = await fetch(`${config.endpoint.replace(/\/$/, '')}/chat/completions`, { method:'POST', headers:{'Content-Type':'application/json', Authorization:`Bearer ${config.key}`}, body:JSON.stringify({model,temperature:.9,messages:[{role:'system',content:'你是平行时空故事设计师。只返回 JSON：{"title":"时空名称","characterNote":"角色在此世界的身份","opening":"第一幕开场"}。不要解释。'},{role:'user',content:`角色真名：${roleName}\n用户真名：${userName}\n角色设定：${owner.details || owner.signature || '暂无'}\n假设：${premise}\n时空风格：${setting || '自然、具体、有情绪'}\n文风名称：${style.name}\n文风要求：${style.prompt}\n人称规则：${narration}\n开场篇幅：约 ${wordCount} 字\n开场要求：${opening || '从一个有画面感的瞬间开始'}\n必须使用以上真名，不要使用任何网名或昵称。`}]}) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data = await response.json(); const raw = String(data.choices?.[0]?.message?.content || '').replace(/```json|```/gi,'').trim(); const generated = JSON.parse(raw); const item = { id:uid(), roleId:owner.id, roleName, userName, premise, setting:setting || '平行世界', writingStyle:style.id, writingStyleName:style.name, writingStylePrompt:style.prompt, wordCount, rolePov, userPov, title:generated.title || premise, characterNote:generated.characterNote || '', opening:generated.opening || opening || '', messages:[] }; state.spaces.push(item); save(); activeId=item.id; page='detail'; } catch (error) { window.alert(`时空生成失败：${error.message}`); } finally { busy=false; render(); } }
  async function sendMessage() { if (busy) return; const space = state.spaces.find(item => item.id === activeId); const owner = roles().find(item => item.id === space?.roleId) || role(); const input = app.querySelector('[data-if-chat-input]'); const content = input?.value.trim(); if (!space || !owner || !content) return; space.messages ||= []; space.messages.push({ role:'user', content }); input.value=''; busy=true; render(); try { const config=window.IdealMachineAPI?.getConfig?.() || {}; const model=window.IdealMachineAPI?.getModel?.('ifshikong') || window.IdealMachineAPI?.getModel?.('chat'); if (!config.endpoint || !config.key || !model) throw new Error('请先配置 if时空的 AI 模型'); const fallbackStyle = resolveWritingStyle(space.writingStyle || 'natural'); const styleName = space.writingStyleName || fallbackStyle.name; const stylePrompt = space.writingStylePrompt || fallbackStyle.prompt; const wordCount = Math.max(50, Math.min(5000, Number(space.wordCount) || 400)); const roleName = roleRealName(owner); const userName = space.userName || userRealName(owner.id); const rolePov = space.rolePov || (space.perspective === 'role' ? space.pov : 'first') || 'first'; const userPov = space.userPov || (space.perspective === 'user' ? space.pov : 'second') || 'second'; const narration = narrationRule(roleName, userName, rolePov, userPov); const response=await fetch(`${config.endpoint.replace(/\/$/, '')}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${config.key}`},body:JSON.stringify({model,temperature:.9,messages:[{role:'system',content:`你正在平行时空“${space.title}”里扮演角色“${roleName}”。用户真名是“${userName}”。角色在这个世界的身份：${space.characterNote}。世界前提：${space.premise}。使用“${styleName}”文风，具体要求：${stylePrompt}。人称规则：${narration}。每次回复控制在约 ${wordCount} 字。全文只能使用角色和用户的真名，不得使用网名或昵称。请始终遵守这个时空，不要提及现实聊天记录、世界书或 AI。`},...space.messages.map(item=>({role:item.role==='user'?'user':'assistant',content:item.content}))]})}); if(!response.ok)throw new Error(`HTTP ${response.status}`); const data=await response.json(); space.messages.push({role:'assistant',content:data.choices?.[0]?.message?.content || '……'}); save(); } catch(error) { space.messages.push({role:'assistant',content:`暂时无法连接这个时空：${error.message}`}); save(); } finally { busy=false; render(); } }
  document.addEventListener('click', event => { if (event.target.closest('[data-app-key="ifshikong"]')) { state=readState(); page='home'; activeId=''; render(); app.classList.add('is-open'); return; } if (!app.classList.contains('is-open')) return; if (event.target.closest('[data-if-close]')) { app.classList.remove('is-open'); return; } if (event.target.closest('[data-if-new]')) { page='create'; render(); return; } if (event.target.closest('[data-if-random]')) { randomizeWorld(); return; } if (event.target.closest('[data-if-home]')) { page='home'; activeId=''; render(); return; } if (event.target.closest('[data-if-role-picker]')) { page='role-picker'; render(); return; } if (event.target.closest('[data-if-close-sheet]')) { page='home'; render(); return; } const selectedRole=event.target.closest('[data-if-role]'); if(selectedRole){state.roleId=selectedRole.dataset.ifRole;save();page='home';render();return;} const opened=event.target.closest('[data-if-open]'); if(opened){activeId=opened.dataset.ifOpen;page='detail';render();return;} const deleted=event.target.closest('[data-if-delete]'); if(deleted){state.spaces=state.spaces.filter(item=>item.id!==deleted.dataset.ifDelete);save();page='home';activeId='';render();return;} if(event.target.closest('[data-if-create]')){createSpace();return;} });
  document.addEventListener('click', event => { if (!app.classList.contains('is-open')) return; if (event.target.closest('[data-if-new]')) createDraft = null; if (!event.target.closest('[data-if-create]')) return; createDraft = { premise:app.querySelector('[data-if-premise]')?.value || '', setting:app.querySelector('[data-if-setting]')?.value || '', opening:app.querySelector('[data-if-opening]')?.value || '', styleId:app.querySelector('[data-if-writing-style]')?.value || 'natural', stylePrompt:app.querySelector('[data-if-style-detail]')?.value || '', wordCount:app.querySelector('[data-if-word-count]')?.value || '1500', rolePov:app.querySelector('[data-if-role-pov]')?.value || 'first', userPov:app.querySelector('[data-if-user-pov]')?.value || 'second' }; }, true);
  document.addEventListener('click', event => { if (!app.classList.contains('is-open')) return; const editor = app.querySelector('[data-if-style-editor]'); const detail = app.querySelector('.ifspace-style-detail'); if (event.target.closest('[data-if-style-new]')) { if (detail) detail.hidden = true; if (editor) editor.hidden = false; const name = app.querySelector('[data-if-style-name]'); const prompt = app.querySelector('[data-if-style-prompt]'); if (name) name.value = ''; if (prompt) prompt.value = ''; name?.focus(); return; } if (event.target.closest('[data-if-style-detail-save]')) { saveCurrentWritingStyle(); return; } if (event.target.closest('[data-if-style-close]')) { if (editor) editor.hidden = true; if (detail) detail.hidden = false; return; } if (event.target.closest('[data-if-style-save]')) saveWritingStyle(); });
  document.addEventListener('click', event => { if (!app.classList.contains('is-open')) return; const panel = app.querySelector('.ifspace-type-panel'); if (event.target.closest('[data-if-typography]')) { if (panel) panel.hidden = !panel.hidden; return; } if (event.target.closest('[data-if-typography-close]') && panel) panel.hidden = true; });
  document.addEventListener('click', event => { if (!app.classList.contains('is-open')) return; if (event.target.closest('[data-if-reroll]')) rerollLatestReply(); });
  document.addEventListener('input', event => { if (!app.classList.contains('is-open')) return; if (event.target.matches('[data-if-font-size]')) { const size = Math.max(12, Math.min(32, Number(event.target.value) || 15)); const output = event.target.parentElement?.querySelector('output'); if (output) output.textContent = `${size}px`; saveTypography({ size }); } if (event.target.matches('[data-if-font-color]')) { const color = event.target.value; const output = event.target.parentElement?.querySelector('output'); if (output) output.textContent = color.toUpperCase(); saveTypography({ color }); } });
  document.addEventListener('change', event => { if (!app.classList.contains('is-open')) return; if (event.target.matches('[data-if-font]')) { saveTypography({ font:event.target.value }); return; } if (event.target.matches('[data-if-font-file]')) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const source = String(reader.result || ''); if (!source) return; saveTypography({ font:'custom', customFontName:file.name.replace(/\.[^.]+$/, ''), customFontSource:source }); render(); const panel = app.querySelector('.ifspace-type-panel'); if (panel) panel.hidden = false; }; reader.onerror = () => window.alert('字体读取失败，请换一个字体文件。'); reader.readAsDataURL(file); } });
  document.addEventListener('submit', event => { if (!app.classList.contains('is-open') || !event.target.matches('[data-if-chat-form]')) return; event.preventDefault(); sendMessage(); });
  window.IdealMachineApps = window.IdealMachineApps || {}; window.IdealMachineApps.ifshikong = { name:'if时空' };
})();
