(() => {
  const storageKey = 'ideal-machine-if-shikong';
  const chatKey = 'ideal-machine-chat';
  const app = document.createElement('div'); app.className = 'ifspace-app'; document.body.appendChild(app);
  let state = readState(); let page = 'home'; let activeId = ''; let busy = false;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  function readState() { try { const value = JSON.parse(localStorage.getItem(storageKey) || '{}'); return { spaces:Array.isArray(value.spaces) ? value.spaces : [], roleId:value.roleId || '' }; } catch { return { spaces:[], roleId:'' }; } }
  function save() { localStorage.setItem(storageKey, JSON.stringify(state)); }
  function readChat() { try { const value = JSON.parse(localStorage.getItem(chatKey) || '{}'); return { contacts:Array.isArray(value.contacts) ? value.contacts : [], profiles:Array.isArray(value.profiles) ? value.profiles : [] }; } catch { return { contacts:[], profiles:[] }; } }
  function roles() { return readChat().contacts; } function role() { return roles().find(item => item.id === state.roleId) || roles()[0]; }
  function avatar(item) { return item?.avatar ? `<img src="${esc(item.avatar)}" alt="">` : esc((item?.nickname || item?.name || '角').slice(0, 1)); }
  function uid() { return `if-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`; }
  function icon(type) { const paths = { plus:'<path d="M24 9v30M9 24h30"/>', back:'<path d="M30 10 16 24l14 14"/>', spark:'<path d="m24 7 4 13 13 4-13 4-4 13-4-13-13-4 13-4z"/>', send:'<path d="m8 23 31-13-9 29-7-13zM8 23l15 3"/>', close:'<path d="m14 14 20 20M34 14 14 34"/>' }; return `<svg viewBox="0 0 48 48" aria-hidden="true">${paths[type] || ''}</svg>`; }
  function rolePicker() { const list = roles(); return `<div class="ifspace-sheet"><div class="ifspace-sheet-backdrop" data-if-close-sheet></div><section><header><h2>选择参与角色</h2><button type="button" data-if-close-sheet>${icon('close')}</button></header><div class="ifspace-role-list">${list.length ? list.map(item => `<button type="button" data-if-role="${esc(item.id)}"><i>${avatar(item)}</i><span><b>${esc(item.nickname || item.name)}</b><small>${esc(item.identity || '角色')}</small></span><em>${item.id === state.roleId ? '✓' : '›'}</em></button>`).join('') : '<p class="ifspace-empty">请先在聊天 App 中添加角色。</p>'}</div></section></div>`; }
  function newSpace() { return `<section class="ifspace-create"><header><button type="button" data-if-home>${icon('back')}</button><div><small>NEW POSSIBILITY</small><h1>创建一个 if 时空</h1></div></header><main><label>这个世界如果……<textarea data-if-premise placeholder="例如：如果我们没有错过"></textarea></label><label>时空风格<input data-if-setting placeholder="例如：温柔日常、末日生存、古代江湖"></label><label>想从哪里开始<input data-if-opening placeholder="例如：第一次在图书馆见面"></label><button class="ifspace-primary" type="button" data-if-create>${icon('spark')} 生成这个时空</button></main></section>`; }
  function spaceCard(item) { return `<button class="ifspace-space-card" type="button" data-if-open="${esc(item.id)}"><i>${icon('spark')}</i><span><b>${esc(item.title || item.premise)}</b><small>${esc(item.setting || '平行世界')} · ${esc(item.roleName || '未选择角色')}</small><p>${esc(item.premise)}</p></span><em>›</em></button>`; }
  function home() { const owner = role(); return `<section class="ifspace-page"><header class="ifspace-header"><div><span>ALTERNATE REALITY</span><h1>if时空</h1><p>去看看，另一种人生会怎样。</p></div><button class="ifspace-close" type="button" data-if-close>×</button></header><main class="ifspace-main"><section class="ifspace-hero"><div><small>WHAT IF</small><h2>每一个如果，都是一条新的时间线。</h2><p>这里的故事和聊天 App 完全分开，不会写入原本的聊天记忆。</p></div><button type="button" data-if-new>${icon('plus')}<span>创建时空</span></button></section><section class="ifspace-owner"><span>参与角色</span><button type="button" data-if-role-picker><i>${avatar(owner)}</i><b>${esc(owner?.nickname || owner?.name || '选择角色')}</b><em>⌄</em></button></section><section class="ifspace-list"><div class="ifspace-section-title"><span>MY TIMELINES</span><b>${state.spaces.length} 条时空</b></div>${state.spaces.length ? state.spaces.slice().reverse().map(spaceCard).join('') : '<div class="ifspace-empty-block"><i>✦</i><p>还没有平行时空<br>从一个“如果”开始吧。</p></div>'}</section></main></section>${page === 'role-picker' ? rolePicker() : ''}`; }
  function detail(space) { const owner = roles().find(item => item.id === space.roleId) || role(); return `<section class="ifspace-detail"><header><button type="button" data-if-home>${icon('back')}</button><div><small>${esc(space.setting || 'ALTERNATE REALITY')}</small><h1>${esc(space.title || '未命名时空')}</h1></div><button type="button" data-if-delete="${esc(space.id)}">×</button></header><main><div class="ifspace-world-card"><span>WORLD PREMISE</span><h2>${esc(space.premise)}</h2><p>${esc(space.opening || '故事从这里开始。')}</p></div><div class="ifspace-character"><i>${avatar(owner)}</i><div><b>${esc(owner?.nickname || owner?.name || '角色')}</b><small>${esc(space.characterNote || '在这个时空里的角色')}</small></div></div><div class="ifspace-message-list">${space.messages?.length ? space.messages.map(item => `<article class="ifspace-message ${item.role === 'user' ? 'is-user' : ''}"><p>${esc(item.content)}</p></article>`).join('') : '<div class="ifspace-empty-chat">时空已经建立。<br>和角色说第一句话吧。</div>'}</div></main><form class="ifspace-composer" data-if-chat-form><input data-if-chat-input placeholder="在这个时空里说点什么…"><button type="submit" aria-label="发送">${icon('send')}</button></form></section>`; }
  function render() { const space = state.spaces.find(item => item.id === activeId); app.innerHTML = page === 'create' ? newSpace() : page === 'detail' && space ? detail(space) : home(); }
  async function createSpace() { if (busy) return; const owner = role(); const premise = app.querySelector('[data-if-premise]')?.value.trim(); const setting = app.querySelector('[data-if-setting]')?.value.trim(); const opening = app.querySelector('[data-if-opening]')?.value.trim(); if (!owner) return window.alert('请先选择一个角色。'); if (!premise) return window.alert('请先写下一个“如果”。'); const config = window.IdealMachineAPI?.getConfig?.() || {}; const model = window.IdealMachineAPI?.getModel?.('ifshikong') || window.IdealMachineAPI?.getModel?.('chat'); if (!config.endpoint || !config.key || !model) return window.alert('请先在设置中配置 if时空的 AI 模型。'); busy = true; render(); try { const response = await fetch(`${config.endpoint.replace(/\/$/, '')}/chat/completions`, { method:'POST', headers:{'Content-Type':'application/json', Authorization:`Bearer ${config.key}`}, body:JSON.stringify({model,temperature:.9,messages:[{role:'system',content:'你是平行时空故事设计师。只返回 JSON：{"title":"时空名称","characterNote":"角色在此世界的身份","opening":"第一幕开场"}。不要解释。'},{role:'user',content:`角色：${owner.nickname || owner.name}\n角色设定：${owner.details || owner.signature || '暂无'}\n假设：${premise}\n时空风格：${setting || '自然、具体、有情绪'}\n开场要求：${opening || '从一个有画面感的瞬间开始'}`}]}) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data = await response.json(); const raw = String(data.choices?.[0]?.message?.content || '').replace(/```json|```/gi,'').trim(); const generated = JSON.parse(raw); const item = { id:uid(), roleId:owner.id, roleName:owner.nickname || owner.name, premise, setting:setting || '平行世界', title:generated.title || premise, characterNote:generated.characterNote || '', opening:generated.opening || opening || '', messages:[] }; state.spaces.push(item); save(); activeId=item.id; page='detail'; } catch (error) { window.alert(`时空生成失败：${error.message}`); } finally { busy=false; render(); } }
  async function sendMessage() { if (busy) return; const space = state.spaces.find(item => item.id === activeId); const owner = roles().find(item => item.id === space?.roleId) || role(); const input = app.querySelector('[data-if-chat-input]'); const content = input?.value.trim(); if (!space || !owner || !content) return; space.messages ||= []; space.messages.push({ role:'user', content }); input.value=''; busy=true; render(); try { const config=window.IdealMachineAPI?.getConfig?.() || {}; const model=window.IdealMachineAPI?.getModel?.('ifshikong') || window.IdealMachineAPI?.getModel?.('chat'); if (!config.endpoint || !config.key || !model) throw new Error('请先配置 if时空的 AI 模型'); const response=await fetch(`${config.endpoint.replace(/\/$/, '')}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${config.key}`},body:JSON.stringify({model,temperature:.9,messages:[{role:'system',content:`你正在平行时空“${space.title}”里扮演角色“${owner.name}”。角色在这个世界的身份：${space.characterNote}。世界前提：${space.premise}。请始终遵守这个时空，不要提及现实聊天记录、世界书或 AI。`},...space.messages.map(item=>({role:item.role==='user'?'user':'assistant',content:item.content}))]})}); if(!response.ok)throw new Error(`HTTP ${response.status}`); const data=await response.json(); space.messages.push({role:'assistant',content:data.choices?.[0]?.message?.content || '……'}); save(); } catch(error) { space.messages.push({role:'assistant',content:`暂时无法连接这个时空：${error.message}`}); save(); } finally { busy=false; render(); } }
  document.addEventListener('click', event => { if (event.target.closest('[data-app-key="ifshikong"]')) { state=readState(); page='home'; activeId=''; render(); app.classList.add('is-open'); return; } if (!app.classList.contains('is-open')) return; if (event.target.closest('[data-if-close]')) { app.classList.remove('is-open'); return; } if (event.target.closest('[data-if-new]')) { page='create'; render(); return; } if (event.target.closest('[data-if-home]')) { page='home'; activeId=''; render(); return; } if (event.target.closest('[data-if-role-picker]')) { page='role-picker'; render(); return; } if (event.target.closest('[data-if-close-sheet]')) { page='home'; render(); return; } const selectedRole=event.target.closest('[data-if-role]'); if(selectedRole){state.roleId=selectedRole.dataset.ifRole;save();page='home';render();return;} const opened=event.target.closest('[data-if-open]'); if(opened){activeId=opened.dataset.ifOpen;page='detail';render();return;} const deleted=event.target.closest('[data-if-delete]'); if(deleted){state.spaces=state.spaces.filter(item=>item.id!==deleted.dataset.ifDelete);save();page='home';activeId='';render();return;} if(event.target.closest('[data-if-create]')){createSpace();return;} });
  document.addEventListener('submit', event => { if (!app.classList.contains('is-open') || !event.target.matches('[data-if-chat-form]')) return; event.preventDefault(); sendMessage(); });
  window.IdealMachineApps = window.IdealMachineApps || {}; window.IdealMachineApps.ifshikong = { name:'if时空' };
})();
