(() => {
  const chatKey = 'ideal-machine-chat';
  const storageKey = 'ideal-machine-ta';
  const app = document.createElement('div'); app.className = 'ta-app'; document.body.appendChild(app);
  const apps = [['liaotian','聊天','chat','#8bb8f1'],['luntan','论坛','forum','#f1a66f'],['rili','日历','calendar','#ee9b9b'],['qinglvkongjian','情侣空间','couple','#dc91b7'],['yinyue','音乐','music','#9e9ae9'],['doubao','豆包','doubao','#8ec8c2'],['gouwu','购物','shop','#e5b27d']];
  let state = readState(); let activeApp = ''; let activeChatTarget = ''; let npcBusy = false; let refreshing = false;
  function readState() { try { return { roleId: JSON.parse(localStorage.getItem(storageKey) || '{}').roleId || '' }; } catch { return { roleId: '' }; } }
  function saveState() { localStorage.setItem(storageKey, JSON.stringify(state)); }
  function read(key, fallback) { try { const value = JSON.parse(localStorage.getItem(key) || 'null'); return value ?? fallback; } catch { return fallback; } }
  function roles() { const data = read(chatKey, {}); return Array.isArray(data.contacts) ? data.contacts : []; }
  function role() { return roles().find(item => item.id === state.roleId) || roles()[0]; }
  function esc(value) { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char])); }
  function avatar(item) { return item?.avatar ? `<img src="${esc(item.avatar)}" alt="">` : esc((item?.nickname || item?.name || 'Ta').slice(0, 1)); }
  function icon(type) { const paths = { chat:'<path d="M8 10h32v22H19l-9 7v-7H8z"/><path d="M15 17h18M15 23h12"/>', forum:'<path d="M9 11h30v21H19l-8 6v-6H9z"/><path d="M16 18h16M16 24h10"/>', calendar:'<rect x="10" y="11" width="28" height="27" rx="4"/><path d="M16 8v7M32 8v7M10 19h28M17 26h.01M24 26h.01M31 26h.01M17 32h.01M24 32h.01"/>', couple:'<path d="M24 38S8 28 8 17a8 8 0 0 1 15-4 8 8 0 0 1 15 4c0 11-14 21-14 21z"/>', music:'<path d="M31 10v22M31 10l9-2v21M31 32c0 4-4 7-8 7s-7-2-7-5 3-6 7-6 8 1 8 4zM40 29c0 4-4 7-8 7"/>', doubao:'<path d="M10 27c0-10 7-17 16-17s12 5 12 13c0 9-7 16-17 16H10z"/><path d="M18 23h.01M30 23h.01M18 30c3 3 7 3 10 0"/>', shop:'<path d="M10 20h28v19H10zM8 20l3-9h26l3 9M16 20v4M24 20v4M32 20v4M16 39V29h16v10"/>' }; return `<svg viewBox="0 0 48 48" aria-hidden="true">${paths[type] || ''}</svg>`; }
  function rolePicker(list) { return `<div class="ta-role-sheet"><div class="ta-role-backdrop" data-ta-role-close></div><section><header><div><small>PHONE OWNER</small><h2>选择角色</h2></div><button type="button" data-ta-role-close>×</button></header><div class="ta-role-list">${list.length ? list.map(item => `<button type="button" data-ta-role="${esc(item.id)}"><i>${avatar(item)}</i><span><b>${esc(item.nickname || item.name)}</b><small>${esc(item.identity || '角色')}</small></span><em>${item.id === state.roleId ? '✓' : '›'}</em></button>`).join('') : '<p class="ta-empty">还没有角色，请先到聊天 App 添加角色。</p>'}</div></section></div>`; }
  function textList(items, empty) { return items.length ? items.map(item => `<article class="ta-role-card"><b>${esc(item.title || item.name || item.nickname || '未命名')}</b><p>${esc(item.text || item.note || item.content || item.artist || '')}</p><small>${esc(item.time || item.date || '')}</small></article>`).join('') : `<p class="ta-role-empty">${empty}</p>`; }
  function chatTarget(owner, target) { const chat = read(chatKey, {}); const current = chat.chats?.[owner.id] || {}; const profile = (chat.profiles || []).find(item => item.id === current.profileId); if (target === 'user') return { id:'user', name:profile?.nickname || profile?.realName || '绑定用户', avatar:profile?.avatar || '', kind:'user', messages:current.messages || [] }; const npcs = npcCache(owner); const item = npcs[Number(target.replace('npc:', ''))]; return item ? { id:target, name:item.name || 'NPC', avatar:item.avatar || '', kind:'npc', identity:item.identity || 'NPC', reason:item.reason || '', messages:[] } : null; }
  function roleConversation(owner, target) { const contact = chatTarget(owner, target); if (!contact) return roleContent('liaotian', owner); const messages = contact.messages || []; return `<section class="ta-role-conversation"><header class="ta-role-conversation-header"><button type="button" data-ta-chat-list>‹</button><div><b>${esc(contact.name)}</b><small>${esc(contact.kind === 'user' ? '绑定用户' : contact.identity || 'NPC')}</small></div><i>${avatar(contact)}</i></header><main>${messages.length ? messages.map(item => `<article class="ta-chat-bubble ${item.role === 'user' ? 'is-user' : 'is-character'}"><p>${esc(item.text || item.content || '')}</p><small>${esc(item.time || '')}</small></article>`).join('') : `<div class="ta-chat-empty"><i>${avatar(contact)}</i><h2>${esc(contact.name)}</h2><p>${contact.kind === 'npc' ? '这是根据局部世界书分析出的联系人，暂时还没有对话记录。' : '还没有和这个联系人开始聊天。'}</p></div>`}</main><footer><span>角色视角 · 只读查看</span></footer></section>`; }
  function worldbook(owner) { const data = read('ideal-machine-worldbooks', {}); return (data.local || []).find(item => item.id === owner.worldbook); }
  function npcCache(owner) { return read('ideal-machine-ta-npcs', {})[owner.id] || []; }
  function snapshot(owner) { return read('ideal-machine-ta-snapshots', {})[owner.id] || {}; }
  async function refreshPhone(owner) { if (refreshing) return; const config = window.IdealMachineAPI?.getConfig?.() || {}; const model = window.IdealMachineAPI?.getModel?.('ta') || window.IdealMachineAPI?.getModel?.('worldbook') || window.IdealMachineAPI?.getModel?.('chat'); if (!config.endpoint || !config.key || !model) return window.alert('请先在设置中配置 AI 接口。'); const chat = read(chatKey, {}); const current = chat.chats?.[owner.id] || {}; const profile = (chat.profiles || []).find(item => item.id === current.profileId); const book = worldbook(owner); refreshing = true; render(); try { const prompt = `请刷新角色“${owner.nickname || owner.name}”手机中的七个 App 内容。根据角色设定、绑定用户和局部世界书生成自然、具体、彼此一致的内容。只返回 JSON，不要 Markdown，格式为：{"npcs":[{"name":"","identity":"","reason":""}],"forum":[{"title":"","text":"","time":""}],"calendar":[{"title":"","text":"","date":""}],"couple":[{"title":"","text":"","date":""}],"music":[{"title":"","text":"","artist":""}],"doubao":[{"title":"","text":""}],"shopping":[{"title":"","text":"","price":""}]}。不要编造与世界书完全无关的重要人物；没有内容的数组返回空数组。\n角色设定：${owner.details || owner.signature || '暂无'}\n绑定用户：${profile?.persona || profile?.nickname || '暂无'}\n局部世界书：${book ? (book.entries || []).map(item => `【${item.name}】${item.content}`).join('\n') : '未绑定局部世界书'}\n已有聊天摘要：${(current.messages || []).slice(-8).map(item => item.text || item.content || '').join('；') || '暂无'}`; const response = await fetch(`${config.endpoint.replace(/\/$/, '')}/chat/completions`, { method:'POST', headers:{'Content-Type':'application/json', Authorization:`Bearer ${config.key}`}, body:JSON.stringify({model, temperature:.8, messages:[{role:'system',content:'你是角色手机内容刷新器，只返回合法 JSON。'},{role:'user',content:prompt}]}) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data = await response.json(); const raw = String(data.choices?.[0]?.message?.content || '').replace(/```json|```/gi,'').trim(); const result = JSON.parse(raw); const all = read('ideal-machine-ta-snapshots', {}); all[owner.id] = result; localStorage.setItem('ideal-machine-ta-snapshots', JSON.stringify(all)); const npcs = read('ideal-machine-ta-npcs', {}); npcs[owner.id] = Array.isArray(result.npcs) ? result.npcs : []; localStorage.setItem('ideal-machine-ta-npcs', JSON.stringify(npcs)); } catch (error) { window.alert(`刷新角色手机失败：${error.message}`); } finally { refreshing = false; render(); } }
  async function analyzeNpcs(owner) { if (npcBusy) return; const book = worldbook(owner); if (!book) return window.alert('这个角色还没有绑定局部世界书。'); const config = window.IdealMachineAPI?.getConfig?.() || {}; const model = window.IdealMachineAPI?.getModel?.('worldbook') || window.IdealMachineAPI?.getModel?.('chat'); if (!config.endpoint || !config.key || !model) return window.alert('请先在设置中配置 AI 接口。'); npcBusy = true; render(); try { const prompt = `请分析角色“${owner.nickname || owner.name}”绑定的局部世界书，提取其中与角色有关、可能出现在角色手机聊天列表里的 NPC。只返回 JSON 数组，每项格式为 {"name":"NPC名称","identity":"身份","reason":"与角色的关系或出现依据"}。不要编造世界书没有依据的重要人物。\n角色设定：${owner.details || owner.signature || '暂无'}\n局部世界书：${(book.entries || []).map(item => `【${item.name}】${item.content}`).join('\n')}`; const response = await fetch(`${config.endpoint.replace(/\/$/, '')}/chat/completions`, { method:'POST', headers:{'Content-Type':'application/json', Authorization:`Bearer ${config.key}`}, body:JSON.stringify({model, temperature:.35, messages:[{role:'system',content:'你是角色手机联系人分析器，只输出合法 JSON。'},{role:'user',content:prompt}]}) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data = await response.json(); const raw = String(data.choices?.[0]?.message?.content || '').replace(/```json|```/gi,'').trim(); const parsed = JSON.parse(raw); const cache = read('ideal-machine-ta-npcs', {}); cache[owner.id] = Array.isArray(parsed) ? parsed : []; localStorage.setItem('ideal-machine-ta-npcs', JSON.stringify(cache)); } catch (error) { window.alert(`NPC 分析失败：${error.message}`); } finally { npcBusy = false; render(); } }
  function roleContent(key, owner) {
    const chat = read(chatKey, {}); const name = owner.nickname || owner.name;
    if (key === 'liaotian') { const current = chat.chats?.[owner.id] || {}; const profile = (chat.profiles || []).find(item => item.id === current.profileId); const npcs = npcCache(owner); const entries = []; entries.push(`<button class="ta-chat-entry" type="button" data-ta-role-chat="user"><i>${avatar(profile)}</i><span><b>${esc(profile?.nickname || profile?.realName || '绑定用户')}</b><small>${esc(current.messages?.at(-1)?.text || current.messages?.at(-1)?.content || '暂无消息')}</small></span><em>›</em></button>`); npcs.forEach((item, index) => entries.push(`<button class="ta-chat-entry" type="button" data-ta-role-chat="npc:${index}"><i>${avatar(item)}</i><span><b>${esc(item.name || 'NPC')}</b><small>${esc(item.identity || item.reason || '由局部世界书分析得到')}</small></span><em>›</em></button>`)); return `<div class="ta-role-intro"><i>${avatar(owner)}</i><div><b>${esc(name)}</b><small>角色手机主人 · 聊天联系人</small></div></div><div class="ta-role-section-head"><b>联系人</b><button type="button" data-ta-analyze-npc ${npcBusy ? 'disabled' : ''}>${npcBusy ? '分析中…' : 'AI 分析局部世界书'}</button></div><div class="ta-chat-entry-list">${entries.join('')}</div>`; }
    const fresh = snapshot(owner);
    if (key === 'luntan') { const posts = fresh.forum?.length ? fresh.forum : read('ideal-machine-forum', []).filter(item => item.ownerType === 'character' || item.owner === name || item.nickname === name); return textList(posts, '角色还没有发布论坛动态。'); }
    if (key === 'rili') { const events = fresh.calendar?.length ? fresh.calendar : read('ideal-machine-calendar-events', []).filter(item => item.contactId === owner.id || item.authorId === owner.id); return textList(events, '角色日历里还没有安排。'); }
    if (key === 'qinglvkongjian') { const couple = read('ideal-machine-couple', {}); const rows = fresh.couple?.length ? fresh.couple : [...(couple.memories || []).map(item => ({...item, title:'回忆 · '+item.title})), ...(couple.wishes || []).map(item => ({...item, title:'愿望 · '+item.text}))]; return `<div class="ta-role-intro"><i>${avatar(owner)}</i><div><b>${esc(name)} 的情侣空间</b><small>角色视角 · 共同记录</small></div></div>${textList(rows, '情侣空间里还没有共同记录。')}`; }
    if (key === 'yinyue') { const music = read('ideal-machine-music', {}); return textList(fresh.music?.length ? fresh.music : music.library?.[owner.id] || [], '角色还没有收藏音乐。'); }
    if (key === 'doubao') { const messages = fresh.doubao?.length ? fresh.doubao : read('ideal-machine-doubao', []).slice(-20).map(item => ({ title: item.role === 'user' ? name : '豆包', text: item.content })); return textList(messages, '角色还没有和豆包聊天。'); }
    const shopping = read('ideal-machine-shopping', {}); const rows = fresh.shopping?.length ? fresh.shopping : [...(shopping.orders?.[owner.id] || []), ...(shopping.wishes?.[owner.id] || [])]; return textList(rows, '角色还没有购物记录。');
  }
  function roleApp(owner) { const meta = apps.find(item => item[0] === activeApp) || apps[0]; if (activeApp === 'liaotian' && activeChatTarget) return roleConversation(owner, activeChatTarget); return `<section class="ta-role-app-page"><header class="ta-role-app-header"><button type="button" data-ta-home>‹</button><div><small>${esc(owner.nickname || owner.name)} 的手机</small><h1>${meta[1]}</h1></div></header><main class="ta-role-app-main"><div class="ta-role-perspective"><span>ROLE VIEW</span><b>正在查看 ${esc(owner.nickname || owner.name)} 的${meta[1]}</b><small>这是角色手机中的内容，不是用户视角</small></div>${roleContent(activeApp, owner)}</main></section>`; }
  function render() { const list = roles(); const owner = role(); if (owner && owner.id !== state.roleId) { state.roleId = owner.id; saveState(); } app.innerHTML = owner && activeApp ? roleApp(owner) : `<section class="ta-phone-page"><div class="ta-wallpaper"></div><header class="ta-phone-status"><span>9:41</span><span>▮▮▮ ◔</span></header><div class="ta-phone-head"><button type="button" data-ta-role-picker><i>${avatar(owner)}</i><span><b>${esc(owner?.nickname || owner?.name || 'Ta 的手机')}</b><small>${owner ? '角色手机' : '还没有角色'}</small></span><em>⌄</em></button><div class="ta-head-actions"><button type="button" data-ta-refresh ${refreshing ? 'disabled' : ''} aria-label="刷新角色手机">${refreshing ? '…' : '↻'}</button><button type="button" class="ta-close" data-ta-close>×</button></div></div><main class="ta-phone-main">${owner ? `<div class="ta-welcome"><span>TA'S PHONE</span><h1>${esc(owner.nickname || owner.name)} 的手机</h1><p>${esc(owner.signature || owner.identity || '这里收纳着角色的日常。')}</p></div><div class="ta-app-grid">${apps.map(([key, name, iconName, color]) => `<button class="ta-app-icon" data-ta-role-app="${key}" type="button"><i style="--ta-icon-color:${color}">${icon(iconName)}</i><span>${name}</span></button>`).join('')}</div>` : `<div class="ta-no-role"><i>⌁</i><h2>还没有角色手机</h2><p>先在聊天 App 中创建一个角色，再来查看 Ta 的手机。</p></div>`}</main></section>${app.classList.contains('is-role-picker') ? rolePicker(list) : ''}`; }
  document.addEventListener('click', event => { if (event.target.closest('[data-app-key="ta"]')) { state = readState(); activeApp = ''; activeChatTarget = ''; render(); app.classList.add('is-open'); return; } if (!app.classList.contains('is-open')) return; if (event.target.closest('[data-ta-close]')) { app.classList.remove('is-open'); app.classList.remove('is-role-picker'); return; } if (event.target.closest('[data-ta-role-picker]')) { app.classList.add('is-role-picker'); render(); return; } if (event.target.closest('[data-ta-role-close]')) { app.classList.remove('is-role-picker'); render(); return; } const selected = event.target.closest('[data-ta-role]'); if (selected) { state.roleId = selected.dataset.taRole; saveState(); app.classList.remove('is-role-picker'); render(); return; } if (event.target.closest('[data-ta-refresh]')) { const owner = role(); if (owner) refreshPhone(owner); return; } if (event.target.closest('[data-ta-chat-list]')) { activeChatTarget = ''; render(); return; } if (event.target.closest('[data-ta-home]')) { activeApp = ''; activeChatTarget = ''; render(); return; } if (event.target.closest('[data-ta-analyze-npc]')) { const owner = role(); if (owner) analyzeNpcs(owner); return; } const chatEntry = event.target.closest('[data-ta-role-chat]'); if (chatEntry) { activeChatTarget = chatEntry.dataset.taRoleChat; render(); return; } const launch = event.target.closest('[data-ta-role-app]'); if (launch) { activeApp = launch.dataset.taRoleApp; activeChatTarget = ''; render(); return; } });
  window.IdealMachineApps = window.IdealMachineApps || {}; window.IdealMachineApps.ta = { name: 'Ta' };
})();
