(() => {
  const key='ideal-machine-music', chatKey='ideal-machine-chat', dbName='ideal-machine-music-files', sessionKey='ideal-machine-netease-session';
  // 与理想机同域部署时保持 '/api'；如果 Worker 是独立域名，可在页面初始化前配置：
  // window.IdealMachineConfig={neteaseApiBase:'https://music-api.example.com'}
  const neteaseApiBase=String(window.IdealMachineConfig?.neteaseApiBase||'https://ideal-machine-music-api.ideal-machine.workers.dev/api').replace(/\/$/,'');
  // 登录认证与音乐数据接口分离；账号和歌单同步仍然走 neteaseApiBase。
  const localAuthApiBase=/^https?:\/\/(?:localhost|127\.0\.0\.1)(?::\d+)?$/i.test(location.origin)?'http://127.0.0.1:3211/api':'https://ideal-machine-music-auth.ideal-machine.workers.dev/api';
  const neteaseAuthApiBase=String(window.IdealMachineConfig?.neteaseAuthApiBase||localAuthApiBase).replace(/\/$/,'');
  const app=document.createElement('div');app.className='music-app';document.body.appendChild(app);
  const audio=new Audio();audio.preload='auto';audio.autoplay=false;audio.playsInline=true;audio.className='music-global-audio';document.body.appendChild(audio);
  const musicRuntimeStyle=document.createElement('style');musicRuntimeStyle.id='music-runtime-controls';musicRuntimeStyle.textContent='.music-app .music-player .music-player-controls button.music-play-control{position:relative!important;display:grid!important;place-items:center!important;box-sizing:border-box!important;width:56px!important;height:56px!important;min-width:56px!important;min-height:56px!important;padding:0!important;border:0!important;border-radius:50%!important;background:#18181a!important;background-color:#18181a!important;color:#fff!important;opacity:1!important;visibility:visible!important;isolation:isolate!important}.music-app .music-player .music-player-controls button.music-play-control::before{position:absolute!important;inset:0!important;z-index:0!important;display:block!important;border-radius:50%!important;background:#18181a!important;content:""!important;pointer-events:none!important}.music-app .music-player .music-player-controls button.music-play-control>svg{position:relative!important;z-index:1!important;display:block!important;width:24px!important;height:24px!important;fill:none!important;stroke:#fff!important;stroke-width:2.4!important;stroke-linecap:round!important;stroke-linejoin:round!important}.music-app .music-player .music-player-controls button.music-play-control>svg.music-primary-control-svg{width:56px!important;height:56px!important}.music-app .music-player .music-player-controls button.music-play-control>svg .music-primary-control-bg{fill:#18181a!important;stroke:none!important}.music-app .music-player .music-player-controls button.music-play-control>svg .music-primary-control-icon{fill:none!important;stroke:#fff!important}.music-app .music-full-lyrics-controls button.is-primary{background:#18181a!important;background-color:#18181a!important;color:#fff!important;border-color:transparent!important}.music-app .music-full-lyrics-controls button.is-primary svg{fill:none!important;stroke:#fff!important}';document.head.appendChild(musicRuntimeStyle);
  audio.dataset.musicUserStart='0';
  document.addEventListener('click',event=>{if(event.target.closest?.('[data-app-key="yinyue"]')){const sharedAutoplay=window.IdealMachineMusicAutoplayOnOpen===true;window.IdealMachineMusicAutoplayOnOpen=false;audio.dataset.musicAutoplayOnOpen=sharedAutoplay?'1':'0';audio.dataset.musicUserStart=sharedAutoplay?'1':'0';}if(event.target.closest?.('[data-music-toggle],[data-music-library-play],[data-music-select],[data-music-playlist-song],[data-music-prev],[data-music-next],[data-music-queue-song],[data-music-desktop-toggle],[data-music-desktop-prev],[data-music-desktop-next]'))audio.dataset.musicUserStart='1';},true);
  audio.addEventListener('play',()=>{if(audio.dataset.musicUserStart!=='1'){audio.pause();playing=false;}});
  let state, page='player', query='', results=[], loading=false, inviteOpen=false, sourceInput='', playing=false, publicLoading=false, loginQr='', loginLoading=false, loginPollToken=0, loginStatus='', neteaseProfile=null, selectedPlaylistId='', lyricsFullOpen=false, searchSource='netease';
  // 公开曲目只在用户主动搜索后载入，不预置在“我的音乐”里。
  let publicTracks=[], lyricRequested=new Set(), lyricLoading=new Set(), queueOpen=false, selectedQueueId='', playMode='list', discRotation=0, desktopLyricsEnabled=localStorage.getItem('ideal-machine-desktop-lyrics')==='1';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>`track-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
  const read=()=>{try{const s=JSON.parse(localStorage.getItem(key)||'{}'),library=s.library||{};Object.keys(library).forEach(id=>{library[id]=Array.isArray(library[id])?library[id].filter(track=>!track?.isPublic&&!['public-william-tell','public-ave-maria'].includes(track?.id)):[];});return {profileId:s.profileId||'',current:s.current||{},rooms:s.rooms||{},library};}catch{return {profileId:'',current:{},rooms:{},library:{}};}};
  const save=()=>localStorage.setItem(key,JSON.stringify(state));
  const profileKey=()=>`ideal-machine-netease-profile-${state?.profileId||'default'}`;
  const readNeteaseProfile=()=>{try{return JSON.parse(localStorage.getItem(profileKey())||'null');}catch{return null;}};
  const saveNeteaseProfile=profile=>{neteaseProfile=profile||null;if(profile)localStorage.setItem(profileKey(),JSON.stringify(profile));else localStorage.removeItem(profileKey());};
  const idb=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(dbName,1);r.onupgradeneeded=()=>r.result.createObjectStore('tracks');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
  const putFile=(id,file)=>idb().then(db=>new Promise((resolve,reject)=>{const r=db.transaction('tracks','readwrite').objectStore('tracks').put(file,id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);}));
  const getFile=id=>idb().then(db=>new Promise((resolve,reject)=>{const r=db.transaction('tracks').objectStore('tracks').get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);}));
  const chat=()=>{try{const s=JSON.parse(localStorage.getItem(chatKey)||'{}');return {profiles:Array.isArray(s.profiles)?s.profiles:[],contacts:Array.isArray(s.contacts)?s.contacts:[],chats:s.chats||{}};}catch{return {profiles:[],contacts:[],chats:{}};}};
  const profile=()=>{const d=chat();if(!state.profileId||!d.profiles.some(x=>x.id===state.profileId))state.profileId=d.profiles[0]?.id||'';return d.profiles.find(x=>x.id===state.profileId)||null;};
  const roles=()=>{const d=chat();return d.contacts.filter(x=>d.chats[x.id]?.profileId===state.profileId);};
  const allRoles=()=>chat().contacts;
  const roleName=id=>{const x=allRoles().find(v=>v.id===id);return x?.nickname||x?.name||'角色';};
  const avatar=x=>x?.avatar?`<img src="${esc(x.avatar)}" alt="">`:esc((x?.nickname||x?.name||'♪').slice(0,1));
  const library=()=>state.library[state.profileId] ||= [];
  const current=()=>state.current[state.profileId]||null;
  const room=()=>state.rooms[state.profileId]||null;
  const icons={search:'<circle cx="21" cy="21" r="10"/><path d="m29 29 10 10"/>',close:'<path d="m15 15 18 18M33 15 15 33"/>',play:'<path d="m18 12 19 12-19 12z"/>',pause:'<path d="M18 13v22M30 13v22"/>',prev:'<path d="M32 13 18 24l14 11zM14 13v22"/>',next:'<path d="M16 13 30 24 16 35zM34 13v22"/>',queue:'<path d="M11 14h22M11 24h22M11 34h14"/>',music:'<path d="M31 10v22a6 6 0 1 1-3-5.2V16l-14 3v16a6 6 0 1 1-3-5.2V15z"/>',users:'<circle cx="17" cy="18" r="6"/><circle cx="33" cy="19" r="5"/><path d="M7 39c1-8 5-11 10-11s9 3 10 11M28 29c6 0 10 3 11 9"/>',user:'<circle cx="24" cy="16" r="7"/><path d="M11 39c1-8 5-11 13-11s12 3 13 11"/>',link:'<path d="M20 28 28 20M18 34l-3 3a7 7 0 0 1-10-10l7-7a7 7 0 0 1 10 0M30 14l3-3a7 7 0 0 1 10 10l-7 7a7 7 0 0 1-10 0"/>'};
  const svg=t=>`<svg viewBox="0 0 48 48">${icons[t]||''}</svg>`;
  const primarySvg=t=>`<svg class="music-primary-control-svg" viewBox="0 0 48 48" aria-hidden="true"><circle class="music-primary-control-bg" cx="24" cy="24" r="23"></circle><g class="music-primary-control-icon">${icons[t]||''}</g></svg>`;
  icons.shuffle='<path d="M8 12h5c5 0 7 24 14 24h5M32 12h-5c-7 0-9 24-14 24H8M28 9l4 3-4 3M28 33l4 3-4 3"/>';
  icons.repeat='<path d="M10 17h22l-4-4M38 31H16l4 4M10 17v7M38 24v7"/>';
  icons.repeatOne='<path d="M10 17h22l-4-4M38 31H16l4 4M10 17v7M38 24v7"/><path d="M24 19v8l-2-2"/>';
  const cover=s=>s.cover?`<img src="${esc(s.cover)}" alt="">`:svg('music');
  const roomStrip=()=>{const r=room(),s=current();if(!r||r.song.id!==s?.id)return '';return `<section class="music-room"><div class="music-room-art">${cover(s)}</div><div class="music-room-copy"><span>LISTENING TOGETHER</span><b>正在和 ${esc(roleName(r.roleId))} 一起听</b><small>${esc(s.title)} · ${esc(s.artist)}</small></div><button data-music-invite type="button">更换</button></section>`;};
  const normalizeLyricLine=line=>{const source=typeof line==='string'?{text:line}:line||{};const text=String(source.text??'').trim();return text?{...source,time:Number(source.time)||0,text}:null;};
  const parseLrc=raw=>String(raw||'').split(/\r?\n/).flatMap(row=>{const tags=[...row.matchAll(/\[(\d+):(\d+(?:\.\d+)?)\]/g)];if(!tags.length)return /^\[[a-z]+:/i.test(row.trim())?[]:(row.trim()?[{time:0,text:row.trim()}]:[]);const text=row.replace(/\[\d+:\d+(?:\.\d+)?\]/g,'').trim();return text?tags.map(tag=>({time:Number(tag[1])*60+Number(tag[2]),text})):[];}).map(normalizeLyricLine).filter(Boolean).sort((a,b)=>a.time-b.time);
  const parseYrc=raw=>String(raw||'').split(/\r?\n/).flatMap(row=>{const header=row.match(/^\[(\d+),(\d+)\](.*)$/);if(!header)return[];const lineTime=Number(header[1])/1000,body=header[3];const words=[];const matcher=/\((\d+),(\d+)\)([^()]*)/g;let match;while((match=matcher.exec(body))){const text=match[3],chars=Array.from(text),start=lineTime+Number(match[1])/1000,duration=Number(match[2])/1000;chars.forEach((char,index)=>words.push({text:char,start:start+duration*index/Math.max(1,chars.length),end:start+duration*(index+1)/Math.max(1,chars.length)}));}const text=words.map(word=>word.text).join('')||body.replace(/\([^)]*\)/g,'').trim();return text?[{time:lineTime,text,words}]:[];}).map(normalizeLyricLine).filter(Boolean).sort((a,b)=>a.time-b.time);
  const lyricLines=s=>{if(Array.isArray(s?.lyrics)&&s.lyrics.length)return s.lyrics.map(normalizeLyricLine).filter(Boolean);const yrc=parseYrc(s?.yrc);if(yrc.length)return yrc;return parseLrc(s?.lyric);};
  const lyricText=line=>{const text=String(line?.text??line??''),words=Array.isArray(line?.words)?line.words:[],chars=Array.from(text);return `<span class="music-lyric-text">${chars.map((char,index)=>{const word=words[index];const start=Number(word?.start),end=Number(word?.end);return `<span class="music-lyric-char" data-lyric-char="${index}"${Number.isFinite(start)?` data-char-start="${start}"`:''}${Number.isFinite(end)?` data-char-end="${end}"`:''}><span class="music-lyric-base">${esc(char)}</span><span class="music-lyric-highlight" aria-hidden="true">${esc(char)}</span></span>`;}).join('')}</span>`;};
  const lyricLineMarkup=(line,index)=>`<p data-music-lyric-line="${index}" data-lyric-time="${Number(line.time)||0}" data-lyric-text="${esc(line.text)}">${lyricText(line)}</p>`;
  const lyricsPanel=s=>{const lines=lyricLines(s),placeholder=lyricLoading.has(s?.id)?'正在同步歌词…':'暂无歌词';return `<section class="music-lyrics" aria-label="歌词"><div class="music-lyrics-window">${lines.length?lines.map(lyricLineMarkup).join(''):`<p class="is-placeholder">${placeholder}</p>`}</div></section>`;};
  const fullLyricsPage=s=>{const lines=lyricLines(s),placeholder=lyricLoading.has(s?.id)?'正在同步歌词…':'暂无歌词';return `<section class="music-full-lyrics-page"><div class="music-full-lyrics-bg">${s.cover?`<img src="${esc(s.cover)}" alt="">`:''}</div><header class="music-full-lyrics-header"><button data-music-lyrics-back type="button" aria-label="返回播放器">‹</button><div><b>歌词</b><small>${esc(s.title)} · ${esc(s.artist||'网易云音乐')}</small></div><button data-music-close type="button" aria-label="关闭音乐">${svg('close')}</button></header><main class="music-full-lyrics-main"><div class="music-full-lyrics-art">${cover(s)}</div><div class="music-full-lyrics-scroll" aria-label="完整歌词">${lines.length?lines.map(lyricLineMarkup).join(''):`<p class="is-placeholder">${placeholder}</p>`}</div></main><footer class="music-full-lyrics-controls"><button data-music-prev type="button" aria-label="上一首">${svg('prev')}</button><button class="is-primary" data-music-toggle type="button" aria-label="${playing?'暂停':'播放'}">${svg(playing?'pause':'play')}</button><button data-music-next type="button" aria-label="下一首">${svg('next')}</button></footer></section>`;};
  function renderDesktopLyrics() { const song=current();let panel=document.querySelector('[data-music-desktop-panel]');if(!desktopLyricsEnabled||!song){panel?.remove();return;}const lines=lyricLines(song),time=Number(audio.currentTime)||0;let active=-1;lines.forEach((line,index)=>{if(Number(line.time)<=time)active=index;});const line=active>=0?lines[active]:lines[0];if(!panel||panel.dataset.songId!==String(song.id)){panel?.remove();panel=document.createElement('aside');panel.className='music-desktop-lyrics';panel.dataset.musicDesktopPanel='';panel.dataset.songId=String(song.id);document.body.appendChild(panel);}panel.innerHTML=`<header><span>桌面歌词</span><button data-music-desktop-close type="button" aria-label="关闭桌面歌词">×</button></header><div class="music-desktop-lyrics-song"><b>${esc(song.title||'')}</b><small>${esc(song.artist||'')}</small></div><p class="music-desktop-lyrics-line" data-music-desktop-line>${esc(line?.text||'暂无歌词')}</p><footer><button data-music-desktop-prev type="button" aria-label="上一首">${svg('prev')}</button><button class="is-primary" data-music-desktop-toggle type="button" aria-label="${playing?'暂停':'播放'}">${svg(playing?'pause':'play')}</button><button data-music-desktop-next type="button" aria-label="下一首">${svg('next')}</button></footer>`;}
  function updateDesktopLyricsLine() { const panel=document.querySelector('[data-music-desktop-panel]'),song=current();if(!panel||!song)return;const lines=lyricLines(song),time=Number(audio.currentTime)||0;let active=-1;lines.forEach((line,index)=>{if(Number(line.time)<=time)active=index;});const line=active>=0?lines[active]:lines[0],target=panel.querySelector('[data-music-desktop-line]');if(target)target.textContent=line?.text||'暂无歌词'; }
  const queuePanel=()=>{const lists=neteaseProfile?.playlists||[],active=lists.find(list=>list.id===selectedQueueId)||lists[0],tracks=active?.tracks||[],currentSong=current();return queueOpen?`<section class="music-queue-panel"><header><select data-music-queue-select aria-label="选择歌单">${lists.length?lists.map(list=>`<option value="${esc(list.id)}" ${list.id===active?.id?'selected':''}>${esc(list.name)}</option>`).join(''):'<option>暂无歌单</option>'}</select><button data-music-queue-close type="button">${svg('close')}</button></header>${tracks.length?tracks.map((song,index)=>{const isCurrent=String(song.id)===String(currentSong?.id),isPlaying=isCurrent&&playing;return `<button class="music-queue-song ${isCurrent?'is-current':''} ${isPlaying?'is-playing':''}" data-music-queue-song="${esc(song.id)}" type="button" aria-label="${isPlaying?'暂停':'播放'} ${esc(song.title)}"><em>${index+1}</em><span><b>${esc(song.title)}</b><small>${esc(song.artist||'网易云音乐')}</small></span><i>${svg(isPlaying?'pause':'play')}</i></button>`;}).join(''):'<p class="music-empty">这个歌单暂时没有歌曲。</p>'}</section>`:'';};
  function player(){const s=current(),r=room();if(!s)return `<section class="music-player-empty"><i>${svg('music')}</i><h2>还没有正在播放的音乐</h2><p>到“我的”导入本地音乐或添加你有授权的音频链接。</p><button data-music-page="my" type="button">打开我的音乐</button></section>`;const stoppedRotation=playing?'':` style="transform:rotate(${discRotation}deg)"`;return `<section class="music-player"><div class="music-turntable ${playing?'is-playing':''}"><div class="music-tonearm" aria-hidden="true"><svg viewBox="0 0 310 250"><circle class="music-tonearm-pivot-ring" cx="155" cy="24" r="19"></circle><circle class="music-tonearm-pivot" cx="155" cy="24" r="10"></circle><g class="music-tonearm-swing"><path class="music-tonearm-arm" d="M155 32 C158 55 165 75 178 88 C194 103 212 103 233 92"></path><path class="music-tonearm-needle" d="M233 87 L240 101"></path><rect class="music-tonearm-head" x="224" y="76" width="21" height="12" rx="3" transform="rotate(25 234.5 82)"></rect></g></svg></div><button class="music-disc ${playing?'is-playing':''}"${stoppedRotation} data-music-open-lyrics type="button" aria-label="打开完整歌词"><div>${cover(s)}</div></button></div><div class="music-player-meta"><h2>${esc(s.title)}</h2><p>${esc(s.artist||'本地音乐')}</p><button class="music-desktop-lyrics-toggle ${desktopLyricsEnabled?'is-enabled':''}" data-music-desktop-lyrics type="button" aria-label="${desktopLyricsEnabled?'关闭桌面歌词':'打开桌面歌词'}" aria-pressed="${desktopLyricsEnabled}">词</button></div><div class="music-progress"><div class="music-progress-times"><span data-music-time-current>0:00</span><span data-music-time-total>0:00</span></div><input data-music-progress type="range" min="0" max="0" step="0.1" value="0" aria-label="播放进度"></div><div class="music-player-controls"><button data-music-prev type="button" aria-label="上一首">${svg('prev')}</button><button class="music-play-control" data-music-toggle type="button" aria-label="${playing?'暂停':'播放'}">${svg(playing?'pause':'play')}</button><button data-music-next type="button" aria-label="下一首">${svg('next')}</button><button class="music-queue-button" data-music-queue type="button" aria-label="歌单">${svg('queue')}</button></div>${queuePanel()}${lyricsPanel(s)}${s.source==='search'?'<small class="music-preview-note">公开试听片段</small>':''}<section class="music-together ${r?.song.id===s.id?'is-active':''}"><div><span>${r?.song.id===s.id?'LISTENING TOGETHER':'LISTEN TOGETHER'}</span><b>${r?.song.id===s.id?`正在和 ${esc(roleName(r.roleId))} 一起听`:'邀请角色一起听'}</b><small>角色会同步看到歌曲与一起听状态。</small></div><button data-music-invite type="button">${svg('users')} ${r?.song.id===s.id?'更换':'邀请'}</button></section></section>`;}
  function search(){return `<section class="music-search"><svg viewBox="0 0 48 48">${icons.search}</svg><span class="music-search-source">网易云音乐</span><input data-music-query value="${esc(query)}" placeholder="搜索网易云歌曲、歌手或专辑"><button data-music-search type="button">搜索</button></section>${loading?'<div class="music-status">正在搜索网易云音乐…</div>':''}${results.length?`<section class="music-results">${results.map(s=>`<article class="music-song"><div class="music-cover">${cover(s)}</div><div><b>${esc(s.title)}</b><small>${esc(s.artist)}${s.album?` · ${esc(s.album)}`:''}</small></div><button data-music-select="${esc(s.id)}" type="button">${svg('play')}</button></article>`).join('')}</section>`:!loading?'<div class="music-empty">输入歌名、歌手或专辑，搜索结果来自网易云音乐。</div>':''}`;}
  function mine(){const list=library();const p=neteaseProfile;return `${p?`<section class="music-netease-profile"><div class="music-netease-avatar">${p.avatarUrl?`<img src="${esc(p.avatarUrl)}" alt="">`:esc((p.nickname||'云').slice(0,1))}</div><div><span>NETEASE CLOUD MUSIC</span><b>${esc(p.nickname||p.userName||'网易云用户')}</b><small>${esc(p.signature||'网易云音乐个人主页已同步')}</small></div><button data-music-profile-refresh type="button">同步</button></section>`:`<section class="music-provider-login"><div class="music-provider-mark"><i></i><i></i><i></i></div><div class="music-provider-copy"><span>NETEASE CLOUD MUSIC</span><b>网易云音乐登录</b><small>${loginLoading?'正在连接，请稍候…':'登录后可同步你的音乐服务。'}</small></div><button data-music-netease-login type="button" ${loginLoading?'disabled':''}>${loginLoading?'正在连接…':'二维码登录'}</button></section>`}${loginQr?`<section class="music-qr-panel"><img src="${esc(loginQr)}" alt="网易云登录二维码"><p role="status">${esc(loginStatus||'请使用网易云音乐 App 扫码登录')}</p></section>`:''}<section class="music-import-actions"><button data-music-import type="button">${svg('music')} 导入本地音乐</button><input data-music-file type="file" accept="audio/*,.flac" multiple hidden></section><section class="music-url-import"><input data-music-url value="${esc(sourceInput)}" placeholder="粘贴 MP3、M4A 等音频链接"><button data-music-add-url type="button">添加</button></section><section class="music-library-list">${list.length?list.map(s=>`<article class="music-song"><div class="music-cover">${cover(s)}</div><div><b>${esc(s.title)}</b><small>${esc(s.artist||'我的音乐库')} · ${s.source==='file'?'本地文件':'授权链接'}</small></div><button data-music-library-play="${esc(s.id)}" type="button">${svg('play')}</button></article>`).join(''):'<div class="music-empty">还没有音乐。导入后可以完整播放并邀请角色一起听。</div>'}</section>`;}
  function tabs(){return `<nav class="music-tabs"><button class="${page==='player'?'is-active':''}" data-music-page="player" type="button">${svg('music')}<small>播放</small></button><button class="${page==='search'?'is-active':''}" data-music-page="search" type="button">${svg('search')}<small>搜索</small></button><button class="${page==='my'?'is-active':''}" data-music-page="my" type="button">${svg('user')}<small>我的</small></button></nav>`;}
  function sheet(){const s=current(),list=allRoles();return `<div class="music-sheet"><div class="music-sheet-mask" data-music-invite-close></div><section><header><div><span>INVITE</span><h2>邀请一起听</h2></div><button data-music-invite-close type="button">${svg('close')}</button></header><div class="music-invite-song"><div>${cover(s)}</div><span><b>${esc(s?.title||'')}</b><small>${esc(s?.artist||'')}</small></span></div><p>所有已创建的角色都可以邀请。</p><div class="music-role-list">${list.length?list.map(r=>`<button data-music-role="${esc(r.id)}" type="button"><i>${avatar(r)}</i><span><b>${esc(r.nickname||r.name)}</b><small>${esc(r.identity||'角色')}</small></span><em>邀请</em></button>`).join(''):'<div class="music-empty">当前还没有创建角色。</div>'}</div></section></div>`;}
  function render(){const p=profile(),song=current();if(p&&page==='player'&&lyricsFullOpen&&song){app.innerHTML=fullLyricsPage(song);renderDesktopLyrics();return;}app.innerHTML=`<section class="music-page"><header class="music-header"><div><span>MUSIC</span><h1>${page==='search'?'搜索音乐':page==='my'?'我的音乐':'音乐播放'}</h1></div><button data-music-close type="button">${svg('close')}</button></header><main class="music-main">${p?(page==='search'?search():page==='my'?mine():player()):'<div class="music-empty">请先在聊天 App 的“我”页面创建用户设定。</div>'}</main>${tabs()}${inviteOpen?sheet():''}</section>`;renderDesktopLyrics();}
  async function api(path,options){const headers={accept:'application/json',...(options?.headers||{})},session=localStorage.getItem(sessionKey),authPath=/^\/auth\/qr\//.test(path)||path==='/auth/logout',base=authPath?neteaseAuthApiBase:neteaseApiBase;if(session&&(path==='/auth/logout'||!authPath))headers.authorization=`Bearer ${session}`;const request=window.IdealMachineFetch||window.fetch.bind(window);const response=await request(`${base}${path}`,{...options,idealScope:'music',credentials:'omit',cache:'no-store',headers});let data=null;try{data=await response.json();}catch{}if(!response.ok)throw new Error(data?.error||`API ${response.status}`);return data;}
  async function neteasePlayUrl(id){const data=await api(`/song/${encodeURIComponent(id)}/url?br=320000`);return data?.data?.[0]?.url||data?.data?.url||data?.url||'';}
  const neteaseOuterUrl=id=>id?`https://music.163.com/song/media/outer/url?id=${encodeURIComponent(id)}.mp3`:'';
  async function activate(song,options={}){const preservedScroll=options.preserveScroll?app.querySelector('.music-main')?.scrollTop:null;let playUrl=song.playUrl||song.preview||song.url||'';try{if(song.source==='file'){const blob=await getFile(song.id);if(!blob)return window.alert('找不到本地音频文件，请重新导入。');playUrl=URL.createObjectURL(blob);}else if(song.source==='netease'&&!playUrl){playUrl=await neteasePlayUrl(song.id);if(!playUrl)return window.alert('当前歌曲没有可用播放地址，请检查网易云账号权限或接口配置。');}}catch(error){return window.alert(`网易云音乐连接失败：${error.message}`);}if(song.source==='netease'&&!song.lyric)lyricRequested.delete(song.id);const activeRoom=room();state.current[state.profileId]={...song,playUrl};if(activeRoom?.roleId)state.rooms[state.profileId]={...activeRoom,song:{...song,playUrl},startedAt:Date.now()};save();audio.pause();audio.src='';audio.load();audio.src=playUrl;audio.load();audio.currentTime=0;if(options.navigate!==false)page='player';render();if(Number.isFinite(preservedScroll))requestAnimationFrame(()=>{const main=app.querySelector('.music-main');if(main)main.scrollTop=preservedScroll;});loadLyrics(state.current[state.profileId]);audio.play().catch(()=>{playing=false;render();window.alert('当前歌曲播放失败，请检查音源是否可用，或点击播放键重试。');});}
  const playbackQueue=()=>{const song=current(),playlists=neteaseProfile?.playlists||[],playlist=playlists.find(list=>list.id===selectedQueueId)||playlists.find(list=>list.tracks?.some(item=>String(item.id)===String(song?.id))),items=playlist?.tracks?.map(item=>({...item,source:'netease'}))||[...library(),...results],seen=new Set();return items.filter(item=>item?.id&&!seen.has(String(item.id))&&(seen.add(String(item.id)),true));};
  function changeTrack(step){const queue=playbackQueue(),song=current(),index=queue.findIndex(item=>String(item.id)===String(song?.id));if(!queue.length||index<0)return window.alert('当前没有可切换的歌曲。');const candidates=queue.filter(item=>String(item.id)!==String(song?.id));const next=playMode==='shuffle'&&candidates.length?candidates[Math.floor(Math.random()*candidates.length)]:queue[(index+step+queue.length)%queue.length];activate(next,{preserveScroll:true});}
  function restartCurrentAfterEnded(){audio.currentTime=0;audio.dataset.musicUserStart='1';audio.play().catch(()=>{playing=false;stopLyricAnimation();if(app.classList.contains('is-open'))render();});}
  function advanceAfterEnded(){const song=current(),queue=playbackQueue();if(playMode==='one'){restartCurrentAfterEnded();return;}if(!queue.length){restartCurrentAfterEnded();return;}const index=queue.findIndex(item=>String(item.id)===String(song?.id));if(index<0){const next=playMode==='shuffle'?queue[Math.floor(Math.random()*queue.length)]:queue[0];activate(next,{preserveScroll:true});return;}const candidates=queue.filter(item=>String(item.id)!==String(song?.id));const next=playMode==='shuffle'&&candidates.length?candidates[Math.floor(Math.random()*candidates.length)]:queue[(index+1)%queue.length];activate(next,{preserveScroll:true});}
  const modeIcon=()=>playMode==='shuffle'?'shuffle':playMode==='one'?'repeatOne':'repeat';
  const modeLabel=()=>playMode==='shuffle'?'随机播放':playMode==='one'?'单曲循环':'列表循环';
  function syncPlaybackModeButton(){const button=app.querySelector('[data-music-mode]');if(!button)return;button.title=modeLabel();button.setAttribute('aria-label',modeLabel());button.innerHTML=svg(modeIcon());}
  function cyclePlayMode(){playMode=playMode==='list'?'shuffle':playMode==='shuffle'?'one':'list';syncPlaybackModeButton();}
  async function restoreCurrent(){let song=current();if(!song)return;let knownUrl=song.playUrl||song.preview||song.url||'';if(!knownUrl&&song.title){let match=null;const term=`${song.title} ${song.artist||''}`;if(song.source==='netease'){try{knownUrl=await neteasePlayUrl(song.id);if(!knownUrl)knownUrl=neteaseOuterUrl(song.id);}catch{}}else if(song.source==='character'||(!song.source&&song.musicTitle)){try{const matches=await searchNetease(term);match=matches.find(item=>item.title===song.title)||matches[0];if(match)knownUrl=await neteasePlayUrl(match.id);if(!knownUrl&&match)knownUrl=neteaseOuterUrl(match.id);}catch{}}else if(song.source==='deezer'){try{match=(await searchDeezer(term))[0];knownUrl=match?.playUrl||'';}catch{}}else if(song.source==='itunes'){try{match=(await searchItunes(term))[0];knownUrl=match?.playUrl||'';}catch{}}if(!knownUrl&&song.source!=='netease'){const fallbacks=[searchDeezer,searchItunes,searchAudius];for(const search of fallbacks){try{const found=await search(term),candidate=found.find(item=>item.playUrl)||found[0];if(candidate?.playUrl){match=candidate;knownUrl=candidate.playUrl;break;}}catch{}}}if(match&&knownUrl){song={...song,...match,playUrl:knownUrl,isPreview:Boolean(match.isPreview||['deezer','itunes'].includes(match.source))};state.current[state.profileId]=song;save();}}if(!knownUrl&&song.source!=='file')return window.alert('这首音乐没有可用播放地址，可能需要登录音乐平台或该歌曲暂不提供试听。');if(audio.src&&knownUrl&&audio.src===knownUrl)return;try{if(song.source==='file'){const blob=await getFile(song.id);if(blob){const playUrl=URL.createObjectURL(blob);if(audio.src&&audio.src===song.playUrl)return;state.current[state.profileId]={...song,playUrl};audio.src=playUrl;save();}}else if(knownUrl){state.current[state.profileId]={...song,playUrl:knownUrl};save();audio.src=knownUrl;audio.load();}}catch{}}
  function deezer(term){return new Promise((resolve,reject)=>{const cb=`idealMusic${Date.now()}${Math.random().toString(36).slice(2)}`,script=document.createElement('script'),timer=setTimeout(()=>{delete window[cb];script.remove();reject(new Error('Deezer 搜索超时'));},15000);window[cb]=d=>{clearTimeout(timer);delete window[cb];script.remove();resolve(d);};script.onerror=()=>{clearTimeout(timer);delete window[cb];script.remove();reject(new Error('Deezer 搜索不可用'));};script.src=`https://api.deezer.com/search?q=${encodeURIComponent(term)}&limit=24&output=jsonp&callback=${cb}`;document.head.appendChild(script);});}
  function itunesSearch(term){return new Promise((resolve,reject)=>{const cb=`idealItunes${Date.now()}${Math.random().toString(36).slice(2)}`,script=document.createElement('script'),timer=setTimeout(()=>{delete window[cb];script.remove();reject(new Error('iTunes 搜索超时'));},15000);window[cb]=d=>{clearTimeout(timer);delete window[cb];script.remove();resolve(d);};script.onerror=()=>{clearTimeout(timer);delete window[cb];script.remove();reject(new Error('iTunes 搜索不可用'));};script.src=`https://itunes.apple.com/search?term=${encodeURIComponent(term)}&entity=song&limit=24&country=CN&callback=${cb}`;document.head.appendChild(script);});}
  function qqSearch(term){return new Promise((resolve,reject)=>{const cb=`idealQQMusic${Date.now()}${Math.random().toString(36).slice(2)}`,script=document.createElement('script'),timer=setTimeout(()=>{delete window[cb];script.remove();reject(new Error('QQ 音乐搜索超时'));},15000);window[cb]=d=>{clearTimeout(timer);delete window[cb];script.remove();resolve(d);};script.onerror=()=>{clearTimeout(timer);delete window[cb];script.remove();reject(new Error('QQ 音乐搜索不可用'));};script.src=`https://c.y.qq.com/splcloud/fcgi-bin/smartbox_new.fcg?key=${encodeURIComponent(term)}&format=jsonp&jsonpCallback=${cb}`;document.head.appendChild(script);});}
  async function searchNetease(term){const data=await api(`/search?keywords=${encodeURIComponent(term)}&limit=24&type=1`),songs=data?.result?.songs||data?.songs||[];return songs.map(x=>{const artists=x.ar||x.artists||[],album=x.al||x.album||{};return {id:String(x.id),title:x.name||'',artist:artists.map(a=>a.name).join(' / '),album:album.name||'',cover:album.picUrl||'',source:'netease'};}).filter(x=>x.title);}
  async function searchDeezer(term){const data=await deezer(term);return (data?.data||[]).map(x=>({id:`deezer-${x.id}`,title:x.title||'',artist:x.artist?.name||'',album:x.album?.title||'',cover:x.album?.cover_medium||x.album?.cover||'',playUrl:x.preview||'',source:'deezer'})).filter(x=>x.title);}
  async function searchItunes(term){const data=await itunesSearch(term);return (data?.results||[]).filter(x=>x.kind==='song').map(x=>({id:`itunes-${x.trackId}`,title:x.trackName||'',artist:x.artistName||'',album:x.collectionName||'',cover:x.artworkUrl100||'',playUrl:x.previewUrl||'',source:'itunes'})).filter(x=>x.title);}
  async function searchQq(term){const data=await qqSearch(term),items=data?.data?.song?.item||[];return items.map(x=>({id:`qq-${x.songmid||x.mid||x.songname}`,title:x.songname||'',artist:(x.singer||[]).map?.(a=>a.name).join(' / ')||'',album:x.albumname||'',cover:'',source:'qq'})).filter(x=>x.title);}
  async function searchAudius(term){const response=await fetch(`https://api.audius.co/v1/search?query=${encodeURIComponent(term)}&app_name=ideal_machine_music`);if(!response.ok)throw new Error(`Audius API ${response.status}`);const data=await response.json();return (data?.data||[]).map(x=>({id:`audius-${x.id}`,title:x.title||'',artist:x.user?.name||'',album:'Audius',cover:x.artwork?.['150x150']||x.artwork?.['480x480']||'',playUrl:x.id?`https://discoveryprovider.audius.co/v1/tracks/${encodeURIComponent(x.id)}/stream?app_name=ideal_machine_music`:'',source:'audius'})).filter(x=>x.title);}
  async function doSearch(){const term=query.trim();if(!term)return;loading=true;results=[];render();try{results=await searchNetease(term);if(!results.length)window.alert('网易云音乐没有找到相关歌曲。');}catch(error){window.alert(`网易云音乐搜索失败：${error.message}`);}finally{loading=false;render();}}
  async function syncNeteaseProfile(){const data=await api('/user/sync');const profile=data?.profile||{},account=data?.account?.account||data?.account||{},vip=data?.vip?.data||data?.vip||{};const playlists=Array.isArray(data?.playlists)?data.playlists:[];const music=playlists.flatMap(list=>Array.isArray(list.tracks)?list.tracks.map(song=>({id:String(song.id||''),title:song.name||'未命名歌曲',artist:song.ar?.map?.(x=>x.name).join(' / ')||song.artist||'',cover:song.al?.picUrl||song.picUrl||''})):[]).filter(song=>song.id);const vipType=profile.vipType??account.vipType??vip.vipType??vip.type??0;const normalized={userId:String(data?.userId||profile.userId||account.id||''),nickname:profile.nickname||account.nickname||'网易云用户',avatarUrl:profile.avatarUrl||account.avatarUrl||'',signature:profile.signature||profile.description||'',level:profile.level||profile.levelInfo?.level||'',vip:Boolean(profile.isVip||profile.vip||account.isVip||vip.isVip||Number(vipType)>0),vipLabel:profile.vipLabel||vip.label||(Number(vipType)>0?'VIP':'普通用户'),music,playlists:playlists.map(list=>({id:String(list.id||''),name:list.name||'未命名歌单',cover:list.coverImgUrl||list.cover||'',trackCount:Number(list.trackCount||list.size||list.tracks?.length||0),tracks:(list.tracks||[]).map(song=>({id:String(song.id||''),title:song.name||'未命名歌曲',artist:song.ar?.map?.(x=>x.name).join(' / ')||song.artist||'',cover:song.al?.picUrl||song.picUrl||''}))}))};saveNeteaseProfile(normalized);render();return normalized;}
  async function neteaseLogin(){
    if(loginLoading)return;
    const token=++loginPollToken;
    loginLoading=true;loginQr='';loginStatus='';render();
    try{
      const keyData=await api('/auth/qr/key');
      if(token!==loginPollToken)return;
      const key=keyData?.data?.unikey||keyData?.unikey;
      if(!key)throw new Error('无法获取登录二维码');
      const qrSessionToken=keyData?.data?.qrSessionToken||keyData?.qrSessionToken;
      if(!qrSessionToken)throw new Error('音乐接口没有建立扫码会话，请稍后重试');
      const qr=await api(`/auth/qr/create?key=${encodeURIComponent(key)}&qrSessionToken=${encodeURIComponent(qrSessionToken)}`);
      if(token!==loginPollToken)return;
      if(!(qr?.data?.qrimg||qr?.qrimg))throw new Error('无法生成登录二维码');
      const qrQuery=`key=${encodeURIComponent(key)}&qrSessionToken=${encodeURIComponent(qrSessionToken)}`;
      loginQr=qr?.data?.qrimg||qr?.qrimg||'';
      loginStatus='请使用网易云音乐 App 扫码登录';render();
      let failures=0;
      const check=async()=>{
        if(token!==loginPollToken||!app.classList.contains('is-open'))return;
        try{
          const status=await api(`/auth/qr/check?${qrQuery}&timestamp=${Date.now()}`);
          if(token!==loginPollToken)return;
          failures=0;
          const code=Number(status?.data?.code??status?.code);
          if(status?.sessionToken||status?.data?.sessionToken){
            localStorage.setItem(sessionKey,status.sessionToken||status.data.sessionToken);
            loginQr='';loginLoading=false;loginStatus='';
            try{await syncNeteaseProfile();lyricRequested.clear();lyricLoading.clear();loadLyrics(current());window.alert('网易云音乐登录成功，个人页面已同步。');}
            catch(error){window.alert(`登录成功，但个人页面同步失败：${error.message}`);}
            render();return;
          }
          if(code===-462){loginQr='';loginLoading=false;render();window.alert('网易云拒绝了当前登录服务（-462）。请确认音乐登录 Worker 已部署最新版本后，再重新生成二维码；手机端不能使用电脑的 127.0.0.1 服务。');return;}
          if(code===803){loginQr='';loginLoading=false;render();window.alert(status?.error||'手机已授权，但音乐接口没有返回登录凭证，请重新扫码。');return;}
          if(code===800){loginQr='';loginLoading=false;render();window.alert('二维码已过期，请重新登录。');return;}
          const upstreamMessage=String(status?.data?.message||status?.message||status?.error||'').trim();
          if(code!==801&&code!==802){
            loginLoading=false;
            loginStatus=upstreamMessage||`网易云登录失败（${code}）`;
            render();
            window.alert(loginStatus);
            return;
          }
          const nextStatus=code===802?'手机已扫码，请在网易云音乐 App 中确认授权':'等待手机扫码…';
          if(loginStatus!==nextStatus){loginStatus=nextStatus;render();}
          setTimeout(check,2000);
        }catch(error){
          if(token!==loginPollToken||error?.name==='AbortError')return;
          failures+=1;
          if(failures<4){loginStatus=`连接中断，正在重试（${failures}/3）…`;render();setTimeout(check,2000);return;}
          loginQr='';loginLoading=false;render();window.alert(`二维码状态检查失败：${error.message}`);
        }
      };
      check();
    }catch(error){if(token!==loginPollToken||error?.name==='AbortError')return;loginQr='';loginLoading=false;render();const message=/failed to fetch/i.test(String(error?.message||''))?(/^https?:\/\/(?:localhost|127\.0\.0\.1)/i.test(neteaseAuthApiBase)?'请先在项目根目录运行：node music-auth-server.mjs':`请确认 ${neteaseAuthApiBase} 已部署，并允许当前网页域名访问。`):error.message||'登录服务不可用，请检查登录后端配置。';window.alert(`网易云登录失败：${message}`);}
  }
  async function logoutNetease(){try{await api('/auth/logout',{method:'POST'});}catch{}localStorage.removeItem(sessionKey);saveNeteaseProfile(null);loginQr='';loginLoading=false;render();window.alert('已彻底退出网易云音乐账号。');}
  async function importFiles(files){const entries=Array.from(files||[]).filter(f=>f.type.startsWith('audio/')||/\.(mp3|m4a|aac|wav|flac|ogg)$/i.test(f.name));if(!entries.length)return;for(const file of entries){const title=file.name.replace(/\.[^.]+$/,'');const track={id:uid(),title,artist:'本地音乐',source:'file'};await putFile(track.id,file);library().push(track);}save();page='my';render();}
  function addUrl(){const url=sourceInput.trim();if(!/^https:\/\//i.test(url))return window.alert('请输入 https 音频链接。');const title=url.split('/').pop().split('?')[0]||'授权音频';library().push({id:uid(),title,artist:'授权音频链接',source:'url',url,playUrl:url});sourceInput='';save();render();}
  async function loadPublicCatalog(){if(publicLoading||publicTracks.some(song=>song.id.startsWith('archive-chopin-')))return;publicLoading=true;try{const response=await fetch('https://archive.org/metadata/musopen-chopin');if(!response.ok)throw new Error('catalog');const data=await response.json();const files=(data.files||[]).filter(file=>/\.mp3$/i.test(file.name||'')).slice(0,80);if(files.length)publicTracks=files.map(file=>{const url=`https://archive.org/download/musopen-chopin/${encodeURIComponent(file.name)}`;return {id:`archive-chopin-${file.name}`,title:String(file.name).replace(/\.mp3$/i,''),artist:'Frédéric Chopin · Musopen',source:'url',url,playUrl:url,isPublic:true};});}finally{publicLoading=false;}}
  document.addEventListener('click',event=>{if(!event.target.closest?.('[data-music-close]'))return;loginPollToken+=1;loginLoading=false;loginQr='';window.IdealMachineCancelRequests?.('music');},true);
  document.addEventListener('click',event=>{if(event.target.closest?.('[data-app-key="yinyue"]')&&audio.dataset.musicAutoplayOnOpen==='1'){audio.dataset.musicSharedPlayPending='1';audio.dataset.musicAutoplayOnOpen='0';}},true);
  document.addEventListener('click',event=>{if(!event.target.closest?.('[data-app-key="yinyue"]')||audio.dataset.musicSharedPlayPending!=='1')return;audio.dataset.musicSharedPlayPending='0';setTimeout(()=>{if(!app.classList.contains('is-open'))return;restoreCurrent().then(()=>{audio.dataset.musicUserStart='1';audio.play().catch(()=>{playing=false;render();});});},0);},true);
  document.addEventListener('click',e=>{const toggle=e.target.closest?.('[data-music-desktop-lyrics]');if(toggle){desktopLyricsEnabled=!desktopLyricsEnabled;localStorage.setItem('ideal-machine-desktop-lyrics',desktopLyricsEnabled?'1':'0');if(desktopLyricsEnabled&&playing)startLyricAnimation();render();return;}const panel=e.target.closest?.('[data-music-desktop-panel]');if(!panel)return;if(e.target.closest('[data-music-desktop-close]')){desktopLyricsEnabled=false;localStorage.setItem('ideal-machine-desktop-lyrics','0');renderDesktopLyrics();if(app.classList.contains('is-open'))render();return;}if(e.target.closest('[data-music-desktop-toggle]')){if(audio.paused)audio.play().catch(()=>window.alert('当前音频无法播放，请检查文件或链接。'));else audio.pause();return;}if(e.target.closest('[data-music-desktop-prev]')){changeTrack(-1);return;}if(e.target.closest('[data-music-desktop-next]')){changeTrack(1);return;}},true);
  document.addEventListener('click',e=>{if(e.target.closest('[data-app-key="yinyue"]')){state=read();profile();save();neteaseProfile=readNeteaseProfile();page=current()?'player':'my';query='';results=[];selectedPlaylistId='';inviteOpen=false;playing=!audio.paused;app.classList.add('is-open');lyricRequested.clear();lyricLoading.clear();render();loadLyrics(current());restoreCurrent().then(()=>{render();loadLyrics(current());});return;}if(!app.classList.contains('is-open'))return;if(e.target.closest('[data-music-close]')){app.classList.remove('is-open');return;}if(e.target.closest('[data-music-toggle]')){if(audio.paused)audio.play().catch(()=>window.alert('当前音频无法播放，请检查文件或链接。'));else audio.pause();return;}const pg=e.target.closest('[data-music-page]');if(pg){page=pg.dataset.musicPage;render();return;}if(e.target.closest('[data-music-search]')){doSearch();return;}if(e.target.closest('[data-music-import]')){app.querySelector('[data-music-file]')?.click();return;}if(e.target.closest('[data-music-add-url]')){addUrl();return;}if(e.target.closest('[data-music-netease-login]')){neteaseLogin();return;}if(e.target.closest('[data-music-profile-refresh]')){syncNeteaseProfile().catch(error=>window.alert(`个人页面同步失败：${error.message}`));return;}const chosen=e.target.closest('[data-music-select]');if(chosen){const s=results.find(x=>x.id===chosen.dataset.musicSelect);if(s)activate(s);return;}const local=e.target.closest('[data-music-library-play]');if(local){const s=library().find(x=>x.id===local.dataset.musicLibraryPlay);if(s)activate(s);return;}if(e.target.closest('[data-music-invite]')){if(!current())return;inviteOpen=true;render();return;}if(e.target.closest('[data-music-invite-close]')){inviteOpen=false;render();return;}const role=e.target.closest('[data-music-role]');if(role){state.rooms[state.profileId]={song:current(),roleId:role.dataset.musicRole,startedAt:Date.now()};save();inviteOpen=false;render();}});
  document.addEventListener('click',e=>{if(e.target.closest('[data-app-key="yinyue"]')){lyricsFullOpen=false;if(app.classList.contains('is-open')){render();updateProgress();}return;}if(e.target.closest('[data-music-close]')){lyricsFullOpen=false;return;}if(!app.classList.contains('is-open'))return;if(e.target.closest('[data-music-page]')){lyricsFullOpen=false;if(page==='player')updateProgress();return;}if(e.target.closest('[data-music-open-lyrics]')){lyricsFullOpen=true;render();loadLyrics(current());updateProgress();return;}if(e.target.closest('[data-music-lyrics-back]')){lyricsFullOpen=false;render();updateProgress();return;}});
  document.addEventListener('input',e=>{if(!app.classList.contains('is-open'))return;if(e.target.matches('[data-music-query]'))query=e.target.value;if(e.target.matches('[data-music-url]'))sourceInput=e.target.value;});
  document.addEventListener('change',e=>{if(!app.classList.contains('is-open'))return;if(e.target.matches('[data-music-source]'))searchSource=e.target.value;});
  document.addEventListener('change',e=>{if(app.classList.contains('is-open')&&e.target.matches('[data-music-file]'))importFiles(e.target.files);});
  document.addEventListener('keydown',e=>{if(app.classList.contains('is-open')&&e.key==='Enter'&&e.target.matches('[data-music-query]'))doSearch();});
  function rememberDiscRotation(){const disc=app.querySelector('.music-turntable .music-disc');if(!disc)return;const matrix=getComputedStyle(disc).transform;if(!matrix||matrix==='none')return;const values=matrix.match(/matrix\(([^)]+)\)/)?.[1]?.split(',').map(Number);if(!values||values.length<6)return;const angle=Math.atan2(values[1],values[0])*180/Math.PI;discRotation=(angle+360)%360;}
  audio.addEventListener('play',()=>{playing=true;startLyricAnimation();renderDesktopLyrics();if(app.classList.contains('is-open')&&page==='player'){if(lyricsFullOpen){syncFullLyricsPlaybackButton();updateLyrics();}else{render();updateProgress();}}});
  audio.addEventListener('pause',()=>{rememberDiscRotation();playing=false;stopLyricAnimation();renderDesktopLyrics();if(app.classList.contains('is-open')&&page==='player'){if(lyricsFullOpen){syncFullLyricsPlaybackButton();updateLyrics();}else{render();updateProgress();}}});
  audio.addEventListener('ended',()=>{playing=false;stopLyricAnimation();renderDesktopLyrics();if(app.classList.contains('is-open')&&page==='player'){if(lyricsFullOpen){syncFullLyricsPlaybackButton();updateLyrics();}else{render();updateProgress();}}});
  document.addEventListener('click',e=>{if(!app.classList.contains('is-open'))return;if(e.target.closest('[data-music-mode]')){cyclePlayMode();return;}if(e.target.closest('[data-music-prev]')){changeTrack(-1);return;}if(e.target.closest('[data-music-next]')){changeTrack(1);return;}if(e.target.closest('[data-music-queue]')){const first=neteaseProfile?.playlists?.[0];if(!selectedQueueId&&first)selectedQueueId=first.id;queueOpen=!queueOpen;render();return;}if(e.target.closest('[data-music-queue-close]')){queueOpen=false;render();return;}const song=e.target.closest('[data-music-queue-song]');if(song){const list=neteaseProfile?.playlists?.find(item=>item.id===selectedQueueId),track=list?.tracks?.find(item=>item.id===song.dataset.musicQueueSong);if(track)activate({...track,source:'netease'},{preserveScroll:true});return;}});
  document.addEventListener('change',e=>{if(!app.classList.contains('is-open')||!e.target.matches('[data-music-queue-select]'))return;selectedQueueId=e.target.value;render();});
  document.addEventListener('input',e=>{if(!app.classList.contains('is-open')||!e.target.matches('[data-music-progress]')||!Number.isFinite(audio.duration))return;audio.currentTime=Number(e.target.value);updateProgress();});
  audio.addEventListener('loadedmetadata',()=>{updateProgress();loadLyrics(current());});audio.addEventListener('timeupdate',updateProgress);audio.addEventListener('ended',advanceAfterEnded);
  function clock(value){if(!Number.isFinite(value)||value<0)return '0:00';const minutes=Math.floor(value/60),seconds=Math.floor(value%60);return `${minutes}:${String(seconds).padStart(2,'0')}`;}
  async function loadLyrics(song){const lyricId=song?.source==='netease'?song.id:song?.musicId;if(!song||!lyricId||song.lyric&&song.lyrics?.length||lyricRequested.has(lyricId))return;lyricRequested.add(lyricId);lyricLoading.add(lyricId);if(current()?.id===song.id&&app.classList.contains('is-open'))render();try{const data=await api(`/lyric/${encodeURIComponent(lyricId)}`),lyric=typeof data?.lrc?.lyric==='string'?data.lrc.lyric:(typeof data?.lyric==='string'?data.lyric:''),yrc=typeof data?.yrc?.lyric==='string'?data.yrc.lyric:(typeof data?.yrc==='string'?data.yrc:'');const lyrics=lyricLines({lyric,yrc});if((lyric||yrc)&&current()?.id===song.id){state.current[state.profileId]={...current(),lyric:lyric||yrc,yrc,lyrics};save();}}catch{lyricRequested.delete(lyricId);}finally{lyricLoading.delete(lyricId);if(current()?.id===song.id&&app.classList.contains('is-open')){render();updateProgress();}}}
  function updateLyrics(){const lines=[...app.querySelectorAll('[data-music-lyric-line]')];if(!lines.length)return;let active=-1,changed=false;lines.forEach((line,index)=>{if(Number(line.dataset.lyricTime)<=audio.currentTime)active=index;});const currentTime=Number(audio.currentTime)||0,currentLineTime=active>=0?Number(lines[active].dataset.lyricTime)||0:0,nextLineTime=active>=0?Number(lines[active+1]?.dataset.lyricTime):NaN;const duration=Number.isFinite(nextLineTime)&&nextLineTime>currentLineTime?nextLineTime-currentLineTime:3.2,isPlayerPreview=page==='player'&&!lyricsFullOpen;lines.forEach((line,index)=>{const shouldBeActive=index===active,chars=[...line.querySelectorAll('.music-lyric-char')],lineColor=shouldBeActive?(isPlayerPreview?'#222':'#fff'):'rgba(255,255,255,.42)';if(shouldBeActive&&!line.classList.contains('is-active'))changed=true;line.classList.toggle('is-active',shouldBeActive);line.classList.remove('is-past');line.style.setProperty('color',lineColor,'important');line.style.setProperty('-webkit-text-fill-color',lineColor,'important');chars.forEach((char,charIndex)=>{const fallbackStart=currentLineTime+duration*charIndex/Math.max(1,chars.length),fallbackEnd=currentLineTime+duration*(charIndex+1)/Math.max(1,chars.length),start=Number(char.dataset.charStart),end=Number(char.dataset.charEnd),charStart=Number.isFinite(start)?start:fallbackStart,charEnd=Number.isFinite(end)&&end>charStart?end:fallbackEnd,amount=!shouldBeActive?0:isPlayerPreview?1:currentTime<=charStart?0:currentTime>=charEnd?1:(currentTime-charStart)/(charEnd-charStart),highlight=char.querySelector('.music-lyric-highlight'),base=char.querySelector('.music-lyric-base');char.style.setProperty('--char-progress',`${Math.max(0,Math.min(1,amount))*100}%`);if(base){base.style.setProperty('color',isPlayerPreview?'#222':'rgba(255,255,255,.42)','important');base.style.setProperty('-webkit-text-fill-color',isPlayerPreview?'#222':'rgba(255,255,255,.42)','important');}if(highlight){highlight.style.setProperty('color',isPlayerPreview?'#222':'#fff','important');highlight.style.setProperty('-webkit-text-fill-color',isPlayerPreview?'#222':'#fff','important');}});});const desktopPanel=document.querySelector('[data-music-desktop-panel]'),desktopLine=desktopPanel?.querySelector('[data-music-desktop-line]'),activeLine=active>=0?lines[active]:null;if(desktopLine&&activeLine)desktopLine.textContent=activeLine.dataset.lyricText||'暂无歌词';const scroller=app.querySelector('.music-full-lyrics-scroll');if(changed&&scroller&&activeLine){const lineRect=activeLine.getBoundingClientRect(),scrollRect=scroller.getBoundingClientRect(),top=scroller.scrollTop+lineRect.top-scrollRect.top-(scroller.clientHeight-lineRect.height)/2;scroller.scrollTo({top:Math.max(0,top),behavior:'smooth'});}}
  function syncFullLyricsPlaybackButton(){const button=app.querySelector('.music-full-lyrics-controls .is-primary');if(!button)return;button.setAttribute('aria-label',playing?'暂停':'播放');button.innerHTML=svg(playing?'pause':'play');}
  function updateProgress(){if(!app.classList.contains('is-open')||page!=='player')return;const range=app.querySelector('[data-music-progress]');if(range){range.max=Number.isFinite(audio.duration)?audio.duration:0;range.value=Number.isFinite(audio.currentTime)?audio.currentTime:0;range.style.setProperty('--music-progress',`${audio.duration?audio.currentTime/audio.duration*100:0}%`);}const currentTime=app.querySelector('[data-music-time-current]'),totalTime=app.querySelector('[data-music-time-total]');if(currentTime)currentTime.textContent=clock(audio.currentTime);if(totalTime)totalTime.textContent=clock(audio.duration);updateLyrics();}
  let lyricAnimationFrame=0;
  function animateLyrics(){lyricAnimationFrame=0;if(!playing||(!app.classList.contains('is-open')&&!desktopLyricsEnabled))return;if(app.classList.contains('is-open')&&page==='player')updateLyrics();if(desktopLyricsEnabled)updateDesktopLyricsLine();lyricAnimationFrame=requestAnimationFrame(animateLyrics);}
  function startLyricAnimation(){if(!lyricAnimationFrame)lyricAnimationFrame=requestAnimationFrame(animateLyrics);}
  function stopLyricAnimation(){if(lyricAnimationFrame){cancelAnimationFrame(lyricAnimationFrame);lyricAnimationFrame=0;}}
  const neteaseAccountCard=p=>`<section class="music-netease-account"><div class="music-netease-account-head"><div class="music-netease-avatar">${p.avatarUrl?`<img src="${esc(p.avatarUrl)}" alt="">`:esc((p.nickname||'云').slice(0,1))}</div><div><span>NETEASE CLOUD MUSIC</span><b>${esc(p.nickname||'网易云用户')}</b><small>${esc(p.signature||'网易云音乐个人主页已同步')}</small></div><em class="${p.vip?'is-vip':''}">${esc(p.vipLabel||'普通用户')}</em></div><div class="music-netease-account-meta"><span>歌单歌曲 <b>${p.music?.length||0}</b></span><span>账号等级 <b>${esc(p.level||'—')}</b></span></div><div class="music-netease-account-actions"><button data-music-profile-refresh type="button">同步个人页</button><button data-music-netease-logout type="button">退出登录</button></div></section>`;
  function decorateNeteasePlaylists(){if(page!=='my'||!neteaseProfile?.playlists?.length)return;const card=app.querySelector('.music-netease-account');if(!card||card.querySelector('.music-netease-playlists'))return;const panel=document.createElement('div');panel.className='music-netease-playlists';const selected=neteaseProfile.playlists.find(list=>list.id===selectedPlaylistId);panel.innerHTML=selected?`<div class="music-netease-playlists-title"><button class="music-playlist-back" data-music-playlist-back type="button">‹ 返回歌单</button><span>${esc(selected.name)} · ${selected.tracks?.length||0} 首</span></div><div class="music-playlist-tracks">${selected.tracks?.length?selected.tracks.map(song=>`<article class="music-song"><div class="music-cover">${cover(song)}</div><div><b>${esc(song.title)}</b><small>${esc(song.artist||'网易云音乐')}</small></div><button data-music-playlist-song="${esc(song.id)}" type="button">${svg('play')}</button></article>`).join(''):'<div class="music-empty">这个歌单暂时没有可播放歌曲。</div>'}</div>`:`<div class="music-netease-playlists-title">我的歌单 <span>${neteaseProfile.playlists.length} 个</span></div>${neteaseProfile.playlists.slice(0,20).map(list=>`<button class="music-netease-playlist" data-music-playlist="${esc(list.id)}" type="button"><div>${list.cover?`<img src="${esc(list.cover)}" alt="">`:svg('music')}</div><span><b>${esc(list.name)}</b><small>${list.trackCount?`${list.trackCount} 首歌曲`:'网易云歌单'}</small></span><em>›</em></button>`).join('')}`;const actions=card.querySelector('.music-netease-account-actions');card.insertBefore(panel,actions);}
  function decorateListeningTogether(){const box=app.querySelector('.music-together');if(!box||box.querySelector('.music-together-people'))return;const r=room(),active=Boolean(r?.song?.id&&r.song.id===current()?.id),me=neteaseProfile?.avatarUrl?`<img src="${esc(neteaseProfile.avatarUrl)}" alt="用户">`:avatar(profile());const role=allRoles().find(item=>item.id===r?.roleId);const other=role?avatar(role):svg('user');const people=document.createElement('div');people.className='music-together-people';people.innerHTML=`<div class="music-together-person"><i>${me}</i><small>我</small></div><span class="music-together-link" aria-label="跳动爱心"><svg viewBox="0 0 58 24" aria-hidden="true"><path class="heartbeat-line" d="M1 12h10l3-7 5 14 5-11 4 4h29"/></svg><span>♥</span></span><div class="music-together-person music-together-role-pick" data-music-invite><i>${other}</i><small>${active?esc(role?.nickname||role?.name||'角色'):'邀请角色'}</small></div>`;const title=box.querySelector('b');if(title)title.textContent=active?`正在和 ${roleName(r.roleId)} 听歌`:'邀请角色一起听';box.prepend(people);}
  function decoratePlaybackControls(){const controls=app.querySelector('.music-player-controls');if(!controls)return;const primary=controls.querySelector('.music-play-control');if(primary){const primaryState=playing?'pause':'play';if(primary.dataset.musicPrimaryState!==primaryState){primary.dataset.musicPrimaryState=primaryState;primary.innerHTML=primarySvg(primaryState);}primary.style.setProperty('display','grid','important');primary.style.setProperty('background','#18181a','important');primary.style.setProperty('color','#fff','important');primary.style.setProperty('border-radius','50%','important');primary.style.setProperty('opacity','1','important');primary.style.setProperty('visibility','visible','important');}if(controls.querySelector('[data-music-mode]'))return;const button=document.createElement('button');button.dataset.musicMode='';button.type='button';button.title=modeLabel();button.setAttribute('aria-label',modeLabel());button.innerHTML=svg(modeIcon());controls.insertBefore(button,controls.querySelector('[data-music-prev]'));}
  function placeLyricsBetween(){const lyrics=app.querySelector('.music-lyrics'),controls=app.querySelector('.music-player-controls'),together=app.querySelector('.music-together');if(!lyrics||!controls||!together)return;const controlsRect=controls.getBoundingClientRect(),togetherRect=together.getBoundingClientRect();if(togetherRect.top>controlsRect.bottom){lyrics.style.left='50%';lyrics.style.top=`${controlsRect.bottom+(togetherRect.top-controlsRect.bottom)/2}px`;}}
  function decorateNeteasePanel(){if(page==='my'&&neteaseProfile){const panel=app.querySelector('.music-netease-profile');if(panel&&!app.querySelector('.music-netease-account'))panel.outerHTML=neteaseAccountCard(neteaseProfile);decorateNeteasePlaylists();}decoratePlaybackControls();decorateListeningTogether();placeLyricsBetween();requestAnimationFrame(()=>requestAnimationFrame(placeLyricsBetween));}
  new MutationObserver(decorateNeteasePanel).observe(app,{childList:true,subtree:true});
  document.addEventListener('click',e=>{if(!app.classList.contains('is-open'))return;if(e.target.closest('[data-music-netease-logout]')){logoutNetease();return;}const playlist=e.target.closest('[data-music-playlist]');if(playlist){selectedPlaylistId=playlist.dataset.musicPlaylist;render();return;}if(e.target.closest('[data-music-playlist-back]')){selectedPlaylistId='';render();return;}const songButton=e.target.closest('[data-music-playlist-song]');if(songButton){const selected=neteaseProfile?.playlists?.find(list=>list.id===selectedPlaylistId),song=selected?.tracks?.find(item=>item.id===songButton.dataset.musicPlaylistSong);if(song){selectedQueueId=selectedPlaylistId;activate({...song,source:'netease'},{navigate:false,preserveScroll:true});}return;}});
  window.addEventListener('resize',placeLyricsBetween);
  function openSharedSong(song) {
    if (!song?.id || song.source !== 'netease' || !song.playUrl) return false;
    state = read();
    profile();
    if (!state.profileId) return false;
    const sharedSong = { ...song, source: 'netease', musicVerified: true };
    state.current[state.profileId] = sharedSong;
    state.rooms[state.profileId] = { song: sharedSong, roleId: song.roleId || state.rooms[state.profileId]?.roleId || '', startedAt: Date.now() };
    save();
    neteaseProfile = readNeteaseProfile();
    page = 'player';
    lyricsFullOpen = false;
    lyricRequested.clear();
    lyricLoading.clear();
    app.classList.add('is-open');
    audio.pause();
    audio.src = '';
    audio.load();
    audio.src = sharedSong.playUrl;
    audio.load();
    audio.currentTime = 0;
    audio.dataset.musicUserStart = '1';
    render();
    loadLyrics(sharedSong);
    audio.play().catch(() => { playing = false; render(); });
    return true;
  }
  window.IdealMachineApps=window.IdealMachineApps||{};window.IdealMachineApps.yinyue={name:'音乐',openSharedSong};
})();
